# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aidialog',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/aidialog',
                'lib_path': 'aidialog'},
  'syms': {'aidialog.core': {'aidialog.core.foo': ('core.html#foo', 'aidialog/core.py')}}}
