"""Messages, dialogs, and attachments: the data model for LLM conversations stored as notebooks

Docs: https://AnswerDotAI.github.io/aidialog/dialog.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_dialog.ipynb.

# %% auto #0
__all__ = ['smsg_types', 'scode', 'snote', 'sprompt', 'sraw', 'MAXLEN', 'AI_RENDERERS', 'INTERRUPTED', 'tiny_png', 'reply_sep',
           'add_id_hash', 'Msgs', 'Dialog', 'mk_output', 'mk_displayobj', 'displayobj', 'mk_code_output', 'code_output',
           'prompt_output', 'Message', 'MsgRow', 'MsgRows', 'get_msg', 'header_info', 'section_msgs', 'get_output_mds',
           'normalize_text_latex', 'render_output_ai', 'render_outputs_ai', 'render_md', 'ai_fmt', 'try_eval',
           'mk_jmsg', 'mk_stream', 'mk_error', 'mk_dispdata', 'mk_execresult', 'dlg2py', 'copy_export', 'merge_metas',
           'merge_parts', 'ruuid4', 'Attachment', 'tool_md', 'usage_md', 'fmt_tools', 'msg2xml', 'RunResult', 'msg2md',
           'dlg2md', 'export_filter']

# %% ../nbs/01_dialog.ipynb #5571d07a
import asyncio, base64, copy, random, re
from ast import literal_eval
from json import loads, dumps
from fastcore.utils import *
from fastcore.meta import delegates
from fastcore.xml import to_xml
from fastcore.tools import lnhash
from fastcore.ansi import strip_ansi
from fastcore.nbio import mk_cell,dir_tag,msg2out,preferred_msg_out,concat_streams,join_out,IMG_MIMES,deep_merge,find_id,Found,render_text,select_cells,item2xml
from .msg_parts import strip_tools as _strip_tools

# %% ../nbs/01_dialog.ipynb #9d79a4b9
smsg_types = scode,snote,sprompt,sraw = "code","note","prompt","raw"

# %% ../nbs/01_dialog.ipynb #61883528
def add_id_hash(cls, attr):
    'Adds `__eq__` and `__hash__` to a cls based on a str or int `attr` id'
    @patch
    def __eq__(self:cls, a):
        if a is None: return False
        if isinstance(a, cls): return getattr(self, attr)==getattr(a, attr)
        if isinstance(a, (str, int)): return getattr(self, attr)==a
        return False
    @patch
    def __hash__(self:cls): return hash(getattr(self, attr))

# %% ../nbs/01_dialog.ipynb #c5da88aa
MAXLEN = 180 # Most characters shown per displayed line

# %% ../nbs/01_dialog.ipynb #352b878b
class Msgs(L):
    "A list of `Message`s with a `preview` repr; index by position, or by message id (exact or unique prefix)"
    def __getitem__(self, k): return find_id(self, k, 'message') if isinstance(k, str) else super().__getitem__(k)

    def _sep(self, m): return ':'
    def show(self,
        maxlen:int=MAXLEN, # Maximum characters per preview line
        rows:int=None, # Max messages to show (None: all)
    ):
        "One `preview` per message: a row line, plus a reply line for prompts"
        xs = list(self) if rows is None else list(self)[:rows]
        res = '\n'.join(m.preview(maxlen, sep=self._sep(m)) for m in xs)
        if rows is not None and len(self)>rows: res += f'\n…({len(self)-rows} more)'
        return PrettyString(res)

    def __repr__(self): return str(self.show(rows=20))

# %% ../nbs/01_dialog.ipynb #bc320318
class Dialog(BasicRepr):
    "A named, ordered list of messages"
    path_ = mtime_ = None  # stamped by `aidialog.ipynb`'s read/write: the file this dialog came from, and its mtime then
    def __init__(self,
        messages=None, # Initial `Message`s, shared not copied: a wrap of live messages is a view over the originals
        name='', # Dialog name, usually the file stem
        meta=None, # Notebook-level metadata dict, carried verbatim through save/load
    ):
        if isinstance(messages, str): raise TypeError("Dialog(messages, name): first arg is the messages - pass name='...' by keyword")
        self.name,self.messages,self.meta = str(name),Msgs(listify(messages)),dict(meta or {})
        for m in self.messages:  # claim only orphans: wrapping live messages must not steal them from their real dialog
            if m.dlg is None: m.dlg = self

    def __len__(self): return len(self.messages)
    def __bool__(self): return True
    def __iter__(self): return iter(self.messages)
    def __getitem__(self, idx): return self.messages[idx]

    def _repr_markdown_(self):
        msgs = ''
        if self.messages:
            msgr = '\n'.join(f'- {o.summ}' for o in self.messages)
            msgs = f'''
<details markdown='1'>

{msgr}

</details>'''
        return f'''
**{self.name}**

{msgs}'''

add_id_hash(Dialog, 'name')

# %% ../nbs/01_dialog.ipynb #3171584d
@patch
def summary(self:Dialog,
    maxlen:int=MAXLEN, # Maximum characters per line
):
    "One `preview` per message: `id:t:content` (t: c=code n=note p=prompt r=raw), plus a `> ` line for a prompt's reply"
    return self.messages.show(maxlen)


# %% ../nbs/01_dialog.ipynb #579ba71b
def mk_output(typ, d, meta=None, **kw): return dict(output_type=typ, metadata=meta or {}, data=d, **kw)
def mk_displayobj(d, meta=None): return mk_output('display_data', d, meta)
def displayobj(data='', subtype='plain', mimetype='text', meta=None): return mk_displayobj({f'{mimetype}/{subtype}': data}, meta)
def mk_code_output(d): return [mk_output('execute_result', d, execution_count=1)]
def code_output(result='', subtype='plain', mimetype='text'): return mk_code_output({f'{mimetype}/{subtype}': result})

def prompt_output(txt=''):
    "Create prompt output list from AI response text"
    return [displayobj(txt, 'markdown', meta={'is_ai_res': True})] if txt else []

# %% ../nbs/01_dialog.ipynb #b25cd968
class Message:
    # Attribute name -> cell metadata key: fields promoted from cell metadata and serialized back (falsy omitted).
    # `skipped` (hidden from AI context) and `pinned` (kept through any context eviction) use solveit's literal keys,
    # so files round-trip between hosts; subclasses may replace the dict wholesale but should keep these two.
    meta_attrs = dict(skipped='skipped', pinned='pinned')
    skipped, pinned = 0, 0  # class-level defaults; instances get real values via `**xtras` or cell metadata
    __skip__ = ['dlg']  # ownership, not message state: `vars_pub` field lists (`flds`, copies) leave it out

    def __init__(self,
        content='', # The message text: markdown, code, or a prompt's request
        dlg=None, # The `Dialog` this message belongs to
        output='', # Jupyter-style output list (code and prompt messages), or ''
        id=None, # Message id; 4 random hex bytes if None
        msg_type='code', # One of `smsg_types`: code, note, prompt, or raw
        attachments=None, # `Attachment`s carried by the message
        meta=None, # Remaining cell metadata, carried verbatim through save/load
        **xtras, # Extra attributes to store as-is
    ):
        "An ipynb cell, or Solveit message (which adds the `prompt` type)"
        # Bare hex, coerced to str: hosts add any display prefix (e.g. solveit's DOM `_`) at their boundary
        id = rtoken_hex(4) if id is None else str(id)
        attachments = listify(attachments)
        meta = dict(meta or {})
        for a,k in self.meta_attrs.items():  # declared fields promote out of `meta` at birth, as on read
            if k in meta: setattr(self, a, meta.pop(k))
        if content  is UNSET: content = ''
        if msg_type is UNSET: msg_type = snote
        if output   is UNSET: output=[] if msg_type in (scode, sprompt) else ''
        self.msg_type = msg_type # Set type first, since it clears output
        self.dlg = dlg
        store_attr(but=['dlg', 'msg_type', 'xtras'])
        for k,v in xtras.items(): setattr(self, k, v)

    # Invalidation hooks, called when output/content/type change; subclasses clear their extra caches here
    def clear_out_cache(self): self._ai_rend = None
    def clear_inp_cache(self): pass

    @DepProp
    def output(self): self.clear_out_cache()

    @output.norm
    def output(self, v):
        if self.msg_type==sprompt and isinstance(v, str): return prompt_output(v)
        return [] if v is None and self.msg_type in (scode, sprompt) else v

    @DepProp
    def content(self): self.clear_inp_cache()

    @DepProp
    def msg_type(self):
        self.clear_out_cache()
        self.clear_inp_cache()
        self.output = [] if self.msg_type in (scode, sprompt) else ''

    @property
    def ai_res(self):
        "Extract AI response text from prompt output list"
        if self.msg_type != sprompt: return ''
        if isinstance(self.output, str): return self.output  # Handle legacy/direct string
        if res := first(L(self.output).filter(lambda x: nested_idx(x, 'metadata', 'is_ai_res'))):
            return nested_idx(res, 'data', 'text/markdown') or ''
        return ''

    def __deepcopy__(self, memo):
        cls = self.__class__
        result = cls.__new__(cls)
        memo[id(self)] = result
        for k, v in self.__dict__.items():
            if k.startswith('_msgidle') or k=='dlg': setattr(result, k, v)
            else: setattr(result, k, copy.deepcopy(v, memo))
        return result

    @property
    def __flds__(self): return vars_pub(self) + ['content', 'output', 'msg_type']
    @property
    def flds(self): return [o for o in self.__flds__ if o not in ('content', 'output', 'attachments')]
    @property
    def summ(self): return truncstr(self.content, 96) + (f" ⇒ {truncstr(str(self.output), 60)}" if self.output else '')
    __repr__ = basic_repr('id,content,output,msg_type')

# %% ../nbs/01_dialog.ipynb #135858d9
add_id_hash(Message, 'id')
Dialog.msg_cls = Message

# %% ../nbs/01_dialog.ipynb #145c8a42
def _prev_line(txt, maxlen, pre=''):
    "One ¶-joined preview line, `pre`+`txt` capped at `maxlen`, ending in a humanized `[size]` when `txt` was cut"
    return truncstr(re.sub(r'\n(?:\s*\n)*', '¶', pre+txt), maxlen, suf=f'…[{humanize(len(txt))}]')

@patch
def preview(self:Message,
    maxlen:int=MAXLEN, # Maximum characters per line
    sep:str=':', # Separator before the content; a find shows `-` on context rows
):
    "Escaped summary rows: `id:t[directives]:content` (t: c=code n=note p=prompt r=raw; the bracket shows meta-form nbdev directives, as in nbio's `CellRow`), plus a `> ` line for a prompt's reply; a contentless tagged raw shows its `<kind>` instead"
    txt = self.content or (f"<{self.meta['rec_kind']}>" if self.meta.get('rec_kind') else '')
    res = _prev_line(txt, maxlen, f"{self.id}:{self.msg_type[0]}{dir_tag(self.meta)}{sep}")
    if self.msg_type==sprompt and self.ai_res: return res + '\n' + _prev_line(self.ai_res, maxlen, '> ')
    if self.output: res += f" ⇒ out({humanize(len(str(self.output)))})"
    return res

Message._repr_markdown_ = Message.preview

# %% ../nbs/01_dialog.ipynb #a72644ce
class MsgRow:
    "Snapshot of one message: `id`, `msg_type`, `content`, `out` (reply or output text), and `meta`; shown as its preview, with `-` in place of the first `:` on a context row"
    def __init__(self, m, maxlen=MAXLEN, kind='match'):
        self.id,self.msg_type,self.content,self.kind = m.id,m.msg_type,m.content,kind
        self.meta = copy.deepcopy(m.meta)
        self.out = (m.ai_res or '') if m.msg_type==sprompt else str(m.output or '')
        self._pv = m.preview(maxlen, sep=':' if kind=='match' else '-')
    def __repr__(self): return self._pv

class MsgRows(Found, L):
    "Find-result `MsgRow`s: index by message id (exact or unique prefix), never by position"
    _unit = 'message'
    def __repr__(self): return '\n'.join(repr(o) for o in self)

# %% ../nbs/01_dialog.ipynb #a0465cdb
@patch
def mk_message(self:Dialog,
    content:str, # Message text
    idx=-1, # Insert position; -1 appends
    after=None, # Insert after this `Message` or id
    before=None, # Insert before this `Message` or id
    msg_type=scode, # One of `smsg_types`
    output='', # Output list; code messages also accept a JSON string
    meta=None, # Cell metadata, carried verbatim through save/load
    export=False, # Also set the meta `nbdev` export flag? (`meta_exported`)
    **kwargs, # Passed to `msg_cls`
):
    "Make new message and insert it into notebook before/after specified cell, or start of list (idx=0) by default"
    if msg_type==scode and isinstance(output,str): output = loads(output or '[]')
    msg = self.msg_cls(content, self, msg_type=msg_type, output=output, meta=meta, **kwargs)
    if export: msg.meta_exported = True
    if 'id' not in kwargs:  # generated ids must not collide, even if the global random stream was re-seeded
        while any(m.id==msg.id for m in self.messages): msg.id = rtoken_hex(4)
    if isinstance(after,  Message): after =after.id
    if isinstance(before, Message): before=before.id
    if after is not None: idx = next((i for i,c in enumerate(self.messages) if c.id==after ), -1)+1
    elif before is not None: idx = next((i for i,c in enumerate(self.messages) if c.id==before), -1)
    if idx==-1: idx=len(self.messages)
    self.messages.insert(idx, msg)
    return msg

# %% ../nbs/01_dialog.ipynb #d499654b
@patch
def mk_messages(self:Dialog, msgs, after=None, before=None):
    "Make new messages and insert them sequentially into the notebook after/before a specific message."
    def _kws(m): return {o: getattr(m,o) for o in m.flds if o!='id'}
    return [after:=self.mk_message(m.content,output=m.output,attachments=m.attachments,after=after, before=before, **_kws(m)) for m in msgs]

# %% ../nbs/01_dialog.ipynb #e668fd4f
@patch
def insert_after(self:Message, msgs):
    curr = self.dlg.messages
    idx = curr.index(self)
    curr[idx+1:idx+1] = msgs
    for m in msgs: m.dlg = self.dlg

# %% ../nbs/01_dialog.ipynb #0c98e2c1
@patch
def _neighbor(self:Message, fwd=True, pred=None):
    "Find next (fwd=True) or previous (fwd=False) message, optionally filtered by pred."
    msgs = self.dlg.messages
    idx = msgs.index(self)
    slc = msgs[idx+1:] if fwd else reversed(msgs[:idx])
    return first(m for m in slc if not pred or pred(m))

@patch
def next(self:Message): return self._neighbor()
@patch
def previous(self:Message): return self._neighbor(fwd=False)
@patch
def rel_msg(self:Message, is_up:bool): return self._neighbor(fwd=not is_up)

# %% ../nbs/01_dialog.ipynb #991f63bc
@patch
def find_msg(self:Dialog, content): return first(m for m in self.messages if m.content==content)

def get_msg(id_, dlg):
    if not dlg or not id_: return
    return first(o for o in dlg.messages if o.id==id_)

# %% ../nbs/01_dialog.ipynb #2b6197c3
@patch
def remove_msgs(self:Dialog, msgs):
    "Remove messages from dialog, return removed list"
    s = set(msgs)
    self.messages[:] = [m for m in self.messages if m not in s]
    return msgs

@patch
def remove_from_dlg(self:Message):
    "Remove this message from its dialog"
    return self.dlg.remove_msgs([self])

# %% ../nbs/01_dialog.ipynb #03ed3d82
_re_hdr = re.compile(r' {0,3}(?P<level>#{1,6})\s+(?P<text>.*)')

def header_info(content):
    "Markdown heading (level, text) of `content`'s first line; (0, None) if not a heading"
    m = _re_hdr.match(content or '')
    return (len(m['level']), m['text']) if m else (0, None)

@patch
def header_level(self:Message):
    "Heading level of a heading note message, else 0"
    return header_info(self.content)[0] if self.msg_type==snote else 0

def section_msgs(ms, head):
    "`head` plus its section in `ms`: messages until the next heading of the same or higher level"
    lvl = head.header_level()
    if not lvl: return Msgs([head])
    ms, res = list(ms), [head]
    for m in ms[ms.index(head)+1:]:
        l = m.header_level()
        if l and l<=lvl: break
        res.append(m)
    return Msgs(res)

# %% ../nbs/01_dialog.ipynb #e074c630
@patch(as_prop=True)
def has_error(self:Message):
    if self.msg_type != scode: return False
    return any(o.get('output_type') == 'error' for o in (self.output or []))

def get_output_mds(output):
    "Extract text/markdown content from code outputs (display_data and execute_result)"
    if not output: return []
    return [o['data']['text/markdown'] for o in output
        if o.get('output_type') in ('display_data', 'execute_result') and 'text/markdown' in o.get('data', {})]

# %% ../nbs/01_dialog.ipynb #4a758426
_display_env = re.compile(r'\\begin\{(align|equation|gather|multline|eqnarray)')

def _latex_parts(s):
    "(display, bare tex) for a Jupyter `text/latex` payload"
    for pat,disp in ((r'\\\[(.*)\\\]', True), (r'\\\((.*)\\\)', False), (r'\$\$(.*)\$\$', True), (r'\$(.*)\$', False)):
        if m := re.fullmatch(pat, s, re.DOTALL): return disp, m.group(1)
    return bool(_display_env.match(s)), s

def normalize_text_latex(s:str, dollars=False):
    r"Canonicalize a `text/latex` payload to `\(...\)`/`\[...\]` delimiters, or `$...$`/`$$...$$` with `dollars`"
    if not s: return s
    disp,tex = _latex_parts(s)
    l,r = (('$$','$$') if disp else ('$','$')) if dollars else ((r'\[',r'\]') if disp else (r'\(',r'\)'))
    return f'{l}{tex}{r}'

AI_RENDERERS = {  # chkstyle: ignore-node
    'text/plain': lambda d: strip_ansi(str(join_out(d))),
    'text/html': join_out,
    'text/markdown': join_out,
    'text/latex': lambda d: normalize_text_latex(join_out(d)),
    'application/javascript': lambda d: f'<script>{join_out(d)}</script>',
}

# %% ../nbs/01_dialog.ipynb #2c4226a7
def render_output_ai(out, renderers=None, dollars=False):
    "Plain-text rendering of one Jupyter output, as the AI sees it; `renderers` overrides/extends the per-mime table and `dollars` picks `$`-spelled math"
    r = AI_RENDERERS | ({'text/latex': lambda d: normalize_text_latex(join_out(d), dollars=True)} if dollars else {}) | (renderers or {})
    ptyp,d = preferred_msg_out(out, html1st=False, include_imgs=False)
    return r.get(ptyp, lambda d: '')(d)

def render_outputs_ai(outputs, renderers=None, dollars=False):
    "Plain-text rendering of a Jupyter output list for LLM context"
    if (not isinstance(outputs, (list,tuple))) or (outputs and not isinstance(outputs[0],dict)):
        print(f"Unexpected outputs: {outputs}")
        return ''
    return '\n'.join(render_output_ai(o, renderers=renderers, dollars=dollars) for o in concat_streams(outputs))

# %% ../nbs/01_dialog.ipynb #11fded06
def _render_md(out, html1st=True):
    "One output as a Markdown part: `('txt',s)` pools into a shared fence, `('md',s)` stands alone"
    mime,d = preferred_msg_out(out, html1st=html1st, include_imgs=True)
    d = join_out(d)
    if not d: return None
    if   mime=='text/plain': return 'txt', strip_ansi(d)
    elif mime=='text/html': return 'md', fenced(d.strip(), '{=html}')
    elif mime=='application/javascript': return 'md', fenced(f'<script>{d}</script>', '{=html}')
    elif mime=='image/svg+xml': return 'md', fenced(d.strip(), '{=html}')
    elif mime in ('text/markdown','text/latex'): return 'md', d.strip()
    elif mime in IMG_MIMES: return 'md', f'![](data:{mime};base64,{"".join(d.split())})'
    return None

def render_md(outputs, html1st=True):
    "Render notebook outputs as Markdown: text to ``` fences, HTML in `{=html}`, markdown inlined, images as data URIs"
    if (not isinstance(outputs, (list,tuple))) or (outputs and not isinstance(outputs[0],dict)): return ''
    parts,buf = [],[]
    def _flush():
        if (txt := ''.join(buf).rstrip()): parts.append(fenced(txt, 'output'))
        buf.clear()
    for out in concat_streams(outputs):
        if not (r := _render_md(out, html1st=html1st)): continue
        k,s = r
        if k=='txt': buf.append(s if s.endswith('\n') else s+'\n')
        else:
            _flush()
            parts.append(s)
    _flush()
    return '\n\n'.join(parts)

# %% ../nbs/01_dialog.ipynb #027d1774
INTERRUPTED = '*[Response interrupted]*'  # marker line hosts append to a reply cut off mid-stream; `ai_fmt` strips it
def ai_fmt(out, strip_tools=False):
    "Format AI response as it will be attached to the chat history"
    res = _strip_tools(out) if strip_tools else out
    res = res.strip().removesuffix('\n'+INTERRUPTED).strip()
    return res or '<output result="pending" reason="incomplete"/>'

# %% ../nbs/01_dialog.ipynb #d42b33a4
_prims = str, int, float, complex, bool, tuple, list, dict, set, frozenset

def try_eval(s, typ:str|None=None):
    "Like `literal_eval`, but wraps in dynamic class named `typ` if succeeds, and returns `s` if fails"
    try:
        res = literal_eval(s)
        if typ and isinstance(res, _prims): res = type(typ, (type(res),), {})(res)
        return res
    except: return s

# %% ../nbs/01_dialog.ipynb #37824d36
Message.ai_renderers = {}

@patch
def render_out(self:Message):
    "Compute and cache the for-AI rendering of this message's output"
    if self._ai_rend is not None: return
    if self.msg_type in (sprompt, scode):
        air = render_outputs_ai(self.output or [], renderers=self.ai_renderers)
        self._ai_rend = ai_fmt(air) if self.msg_type == sprompt else str(try_eval(air))
    else: self._ai_rend = ''

@patch(as_prop=True)
def ai_output(self:Message):
    self.render_out()
    return self._ai_rend

# %% ../nbs/01_dialog.ipynb #c09bb8be
def mk_jmsg(typ, metadata=None, **kwargs):
    "A minimal Jupyter iopub message dict of type `typ`, with `kwargs` as its content"
    kwargs['metadata'] = metadata or {}
    return {'msg_type':typ, 'content':kwargs, 'header':{'msg_type':typ}}

def mk_stream(text, name='stdout'): return mk_jmsg('stream', name=name, text=text)
def mk_error(ename='Exception', evalue='', traceback=None): return mk_jmsg('error', ename=ename, evalue=evalue, traceback=traceback or [])
def mk_dispdata(data, metadata=None, display_id=None):
    return mk_jmsg('display_data', data=data, metadata=metadata, transient={'display_id':display_id} if display_id else {})
def mk_execresult(data, metadata=None, execution_count=1):
    return mk_jmsg('execute_result', data=data, metadata=metadata, execution_count=execution_count)

# %% ../nbs/01_dialog.ipynb #eb52bbdb
@patch
def clear_output(self:Message, wait=False):
    "Clear outputs now, or on the next `add_output` if `wait`"
    self._clear_pending = wait
    if not wait: self.output = [] if self.msg_type in (scode, sprompt) else ''

@patch
def add_output(self:Message,
    jmsg, # A Jupyter iopub message dict
    trunc=None, # Optional transform applied to each new output dict, e.g. truncation
    on_input=None, # Optional handler for kernel `input_request` messages
):
    "Convert iopub message `jmsg` to an output dict and add it to this message's outputs"
    if not self.output: self.output = []
    self.clear_out_cache()
    if getattr(self, '_clear_pending', False): self.clear_output()
    mt = jmsg['header']['msg_type']
    if mt=='execute_result' and self.content.rstrip().endswith(';'): return
    if mt=='input_request': return on_input(jmsg) if on_input else None
    display_id = nested_idx(jmsg, 'content', 'transient', 'display_id')
    if isupd := mt=='update_display_data':
        assert display_id
        jmsg['msg_type'] = jmsg['header']['msg_type'] = 'display_data'
    out = msg2out(jmsg)
    if trunc: out = trunc(out)
    if display_id: out['metadata']['did'] = display_id
    if isupd:
        for i,o in enumerate(self.output):
            if nested_idx(o, 'metadata', 'did')==display_id:
                self.output[i] = out
                return
    self.output.append(out)

# %% ../nbs/01_dialog.ipynb #08680316
@patch(as_prop=True)
def directives(self:Message):
    "nbdev directives from content comments and the meta `nbdev` dict, comments winning"
    return mk_cell(self.content, metadata=self.meta).directives

def _get_exported(self): return 'export' in self.directives or 'exports' in self.directives
Message.exported = property(_get_exported,
    doc="Whether this message carries an nbdev export directive, in content or meta (read-only: edit content, or assign `meta_exported`)")

def _get_mexp(self): return any(k in self.meta.get('nbdev',{}) for k in ('export','exports'))
def _set_mexp(self, v):
    if v: self.meta.setdefault('nbdev',{})['export'] = 'true'
    else:
        nbd = self.meta.get('nbdev',{})
        for k in ('export','exports'): nbd.pop(k, None)
        if not nbd: self.meta.pop('nbdev', None)
Message.meta_exported = property(_get_mexp, _set_mexp,
    doc="The meta `nbdev` export entry alone - the host-owned switch; assigning writes or clears only meta, never content")

def dlg2py(dlg):
    "The exported code of `dlg`, as a python source string"
    return '\n\n'.join(m.content for m in dlg.messages if m.msg_type==scode and m.exported)

# %% ../nbs/01_dialog.ipynb #d905dc3f
@patch
def directive(self:Message, name, default=None):
    "Value of directive `name` (`''` if bare), or `default` if absent"
    return self.directives.get(name, default)

@patch
def has_directive(self:Message, name):
    "Does this message carry directive `name`, in content or meta?"
    return name in self.directives

# %% ../nbs/01_dialog.ipynb #e4fb159d
@patch
def update(self:Message,
    mergemeta:dict=None, # `deep_merge` into `meta`; a `None` value deletes its key
    export:bool=None, # Add (True) or remove (False) the nbdev export directive; a content-form line migrates to meta
    **kwargs, # Attributes to assign, e.g. `content=`, `msg_type=`, `output=`, or `meta=` (replacing it wholesale)
):
    "Update this message's attributes; returns self"
    for k, v in kwargs.items():
        if not (hasattr(self, k) or k in self.meta_attrs):
            raise AttributeError(f'{k!r} is not a declared Message field; use mergemeta= for custom metadata')
        if v is not UNSET: setattr(self, k, v)
    if mergemeta is not None: self.meta = deep_merge(self.meta, mergemeta)
    if export is not None:
        c = mk_cell(self.content)
        d = c.directives
        if d.pop('export', None) is not None or d.pop('exports', None) is not None:
            c.directives = d
            self.content = c.source
        self.meta_exported = export
    return self

# %% ../nbs/01_dialog.ipynb #0db3221b
_re_exp = re.compile(r'#\|\s*exports?[^\n]*\n')

def copy_export(s, src):
    "Prepend `src`'s leading export directive line to `s`, unless `s` already starts with a `#|` directive"
    m = _re_exp.match(src)
    return m.group(0)+s if m and not s.startswith('#|') else s

# %% ../nbs/01_dialog.ipynb #860657a4
@patch
def merge_content(self:Message,
    mtype:str, # The merge target's msg_type
):
    "This message's content contribution when merged into a `mtype` message; hosts override for their own conventions"
    if mtype==scode: return self.content
    if self.msg_type==sprompt: return f'## AI Prompt\n{self.content}\n## AI Response\n{self.ai_res}'
    if self.msg_type==scode: return f'```python\n{self.content}\n```'
    if self.msg_type==sraw: return f'```plaintext\n{self.content}\n```'
    return self.content

# %% ../nbs/01_dialog.ipynb #c201c787
def merge_metas(metas):
    "First-wins merge of cell metadata dicts, merging the `nbdev` directives dict one level deeper"
    res,nbd = {},{}
    for meta in metas:
        for k,v in (meta or {}).items():
            if k=='nbdev':
                for dk,dv in v.items(): nbd.setdefault(dk,dv)
            else: res.setdefault(k,v)
    if nbd: res['nbdev'] = nbd
    return res

def merge_parts(msgs, srcs=None):
    "Merged `(content, meta)` for combining `msgs` (optionally with per-message rendered `srcs`): later messages' directive lines fold into the merged meta, first message winning conflicts"
    if srcs is None: srcs = [m.content for m in msgs]
    cells = [mk_cell(s) for s in srcs]
    for c in cells[1:]: c.remove_directives()
    meta = merge_metas([{**m.meta, 'nbdev': {k: x or 'true' for k,x in m.directives.items()}} for m in msgs])
    nbd = {k:x for k,x in meta.get('nbdev',{}).items() if k not in cells[0].directives}
    if nbd: meta['nbdev'] = nbd
    else: meta.pop('nbdev', None)
    return '\n\n'.join(c.source for c in cells), meta

# %% ../nbs/01_dialog.ipynb #c872b4ee
_out_types = {'stream','display_data','execute_result','error'}

@patch
def validate(self:Message):
    "Raise `ValueError` for problems that would break saving or rendering; returns self if fine"
    if self.msg_type not in smsg_types: raise ValueError(f"{self.id}: unknown msg_type {self.msg_type!r}")
    if not (self.id and isinstance(self.id, str)): raise ValueError(f"message missing id: {truncstr(self.content, 30)!r}")
    if not isinstance(self.content, str): raise ValueError(f"{self.id}: content must be str")
    o = self.output
    if self.msg_type in (scode, sprompt):
        if not isinstance(o, list): raise ValueError(f"{self.id}: {self.msg_type} output must be a list")
        if bad := first(x for x in o if not (isinstance(x, dict) and x.get('output_type') in _out_types)):
            raise ValueError(f"{self.id}: bad output entry {truncstr(str(bad), 50)!r}")
    elif o: raise ValueError(f"{self.id}: {self.msg_type} message must not carry output")
    try: dumps(self.meta)
    except TypeError as e: raise ValueError(f"{self.id}: meta not JSON-serializable: {e}") from None
    return self

# %% ../nbs/01_dialog.ipynb #d07ccb3d
@patch
def validate(self:Dialog):
    "Validate every message plus dialog-scope rules (unique ids, serializable `meta`); returns self if fine"
    ids = [m.id for m in self.messages]
    if dups := {i for i in ids if ids.count(i)>1}: raise ValueError(f"duplicate message id(s): {', '.join(sorted(dups))}")
    for m in self.messages: m.validate()
    try: dumps(self.meta)
    except TypeError as e: raise ValueError(f"dialog meta not JSON-serializable: {e}") from None
    return self

# %% ../nbs/01_dialog.ipynb #1c03c386
def ruuid4():
    "Generate a deterministic UUID4-like string using rtoken_hex"
    parts = [rtoken_hex(4), rtoken_hex(2), rtoken_hex(2), rtoken_hex(2), rtoken_hex(6)]
    parts[2], parts[3] = '4' + parts[2][1:], format(random.randint(8, 11), 'x') + parts[3][1:]
    return f"{parts[0]}-{parts[1]}-{parts[2]}-{parts[3]}-{parts[4]}"

class Attachment(BasicRepr):
    def __init__(self, data:bytes, content_type:str, id:str=''):
        id = str(id) if id else ruuid4()
        store_attr()

add_id_hash(Attachment, 'id')

@patch
def mk_attachment(self:Message, data:bytes, content_type:str, id:str=''):
    att = Attachment(data=data, content_type=content_type, id=id)
    return self.attachments.append(att)

# %% ../nbs/01_dialog.ipynb #18689653
tiny_png = base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==')

# %% ../nbs/01_dialog.ipynb #036da886
@patch
def todict(self:Dialog): return {k:v for k,v in asdict(self).items() if k[0]!='_'}

# %% ../nbs/01_dialog.ipynb #63c06529
@patch
def todict(self:Message):
    "Public stored fields plus the derived `exported` flag, with `output` as the AI-facing form"
    res = AttrDict({k:v for k,v in asdict(self).items() if k[0]!='_' and k!='attachments'})
    res['output'] = self.ai_output
    res['exported'] = self.exported
    return res

# %% ../nbs/01_dialog.ipynb #ca70a93e
from .msg_parts import tool_info as _tool_info, usage_info as _usage_info

def _fmt_param(v, mx=40):
    "Compact display form of one tool arg or result value"
    s = v if isinstance(v, str) else dumps(v, ensure_ascii=False)
    s = re.sub(r'\n(?:\s*\n)*', '¶', s)
    if len(s) > mx: s = s[:mx] + '…'
    return dumps(s, ensure_ascii=False)

def _code_span(txt):
    "Wrap `txt` in a backtick span longer than any backtick run inside it"
    ticks = '`'*(max(map(len, re.findall('`+', txt)), default=0)+1)
    pad = ' ' if '`' in txt else ''
    return f"{ticks}{pad}{txt}{pad}{ticks}"

_code_args = {'py':'code', 'python':'code', 'bash':'cmd'}

def tool_md(d):
    "Display markdown for one parsed `{.tool}` block: a folded details div labeled `func(params)→result`, code tools shown as code"
    params = ', '.join(f"{k}={_fmt_param(v)}" for k,v in (d.get('args') or {}).items())
    res = d.get('result')
    tail = f"→{_fmt_param(res)}" if res not in (None, '') else ''
    label = _code_span(f"{d.get('name')}({params}){tail}")
    code = (d.get('args') or {}).get(_code_args.get(d.get('name'), ''))
    if code is not None:
        body = f"Code:\n{fenced(str(code), d.get('name'))}"
        if str(res or '').strip(): body += f"\n\nOutput:\n\n{fenced(str(res))}"
    else: body = fenced(dumps(d, indent=2, ensure_ascii=False), 'json')
    return fenced(f"## {label}\n\n{body}", ' {.details .tool-usage-details}', ch=':')

def usage_md(d):
    "Display markdown for one parsed `{.usage}` block: a folded details div labeled with cost or tokens"
    summ = d.get('summary') or (f"${d['cost']:.4f}" if d.get('cost') else f"{d.get('total_tokens', 0):,} tokens")
    det = d.get('detail') or ' | '.join(f"{k}={v:,}" if isinstance(v, int) else f"{k}={v}"
                                        for k,v in d.items() if v and k != 'model')
    body = f"## {summ}\n\n{_code_span(det)}"
    return fenced(body, ' {.details .token-usage-details}', ch=':')

def fmt_tools(s):
    "Rewrite fenced JSON tool/usage wire blocks in `s` into folded `::: details` display markdown"
    out, pos = [], 0
    for info,body,start,end in fenced_blocks(s):
        if info not in (_tool_info, _usage_info): continue
        try: d = loads(body)
        except Exception: continue
        out.append(s[pos:start])
        out.append((tool_md(d) if info == _tool_info else usage_md(d)) + '\n')
        pos = end
    out.append(s[pos:])
    return ''.join(out)

# %% ../nbs/01_dialog.ipynb #4b5ff75b
_t2tag = dict(note='markdown')

def msg2xml(m, incl_out=False, trunc_out=True, ids=True):
    "One message as concise XML: content bare inside its type tag, an `<out>` section for a code output or a prompt's reply, and meta `nbdev` directives as attrs (a meta-exported message gets a bare `export`)"
    if m.msg_type==sprompt: o = m.ai_res
    elif incl_out and m.msg_type==scode and m.output:
        o = render_outputs_ai(m.output)
        if trunc_out: o = truncstr(o, 512)
    else: o = ''
    it = item2xml(_t2tag.get(m.msg_type, m.msg_type), m.content, o, id=m.id if ids else None,
        kind=m.meta.get('rec_kind'), meta=m.meta)
    return to_xml(it, do_escape=False)

@patch
def to_xml(self:Message, incl_out=False, trunc_out=True, ids=True):
    "This message as concise XML (`msg2xml`)"
    return msg2xml(self, incl_out, trunc_out, ids)

# %% ../nbs/01_dialog.ipynb #5608b173
@patch
def view(self:Dialog,
    incl_out:bool=False, # Include code outputs?
    only_errors:bool=False, # Show only code messages with error outputs (implies `incl_out`)?
    trunc_out:bool=True, # Truncate each output to ~512 chars?
):
    "This dialog as concise XML; meta-exported messages carry a bare `export` attr"
    ms = [m for m in self.messages if m.has_error] if only_errors else self.messages
    body = ''.join(msg2xml(m, incl_out or only_errors, trunc_out) for m in ms)
    return PrettyString(f'<dialog name="{self.name}">{body}</dialog>')

# %% ../nbs/01_dialog.ipynb #226893ea
@patch
def view(self:Message,
    nums:bool=True, # Show line numbers?
    start_line:int=1, # Starting line to view
    end_line:int=None, # End line (defaults to last line if None; -1 for EOF)
    lnhashs:bool=False, # Show exhash `lineno|hash|` addresses instead of line numbers?
    incl_out:bool=False, # Append the output (a prompt's reply, or code outputs) in an `<out>` block?
    trunc_out:bool=True, # Truncate an included output to ~512 chars?
):
    "This message's content with optional line numbers or exhash addresses"
    lines = self.content.splitlines()
    lines = lines[start_line-1:len(lines) if end_line in (None,-1) else end_line]
    res = '\n'.join((lnhash(i,l)+l if lnhashs else f'{i}: {l}' if nums else l) for i,l in enumerate(lines, start_line))
    if incl_out:
        o = self.ai_res if self.msg_type==sprompt else render_outputs_ai(self.output) if self.msg_type==scode and self.output else ''
        if o: res += f"\n<out>\n{truncstr(o, 512) if trunc_out else o}\n</out>"
    return PrettyString(res)

# %% ../nbs/01_dialog.ipynb #0daf0581
reply_sep = "\n\n##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->\n\n"

@patch(as_prop=True)
def cell_type(self:Message):
    "This message's notebook cell type"
    return 'markdown' if self.msg_type in (snote,sprompt) else self.msg_type

@patch(as_prop=True)
def source(self:Message):
    "This message's cell source: `content`, with a prompt's reply appended as it serializes"
    cts = self.content or ''
    if self.msg_type==sprompt and (o := self.ai_res): cts = cts + reply_sep + o
    return cts

@patch(as_prop=True)
def cells(self:Dialog):
    "Messages as cells: dialogs duck-type as notebooks for read-only notebook consumers"
    return self.messages

# %% ../nbs/01_dialog.ipynb #7d6cd4cd
class RunResult(Msgs):
    "Messages run by `Dialog.execute`, shown as a status report"
    def __init__(self, items=None, head=False):
        super().__init__(items)
        self.head = head
    def _line(self, m, maxlen):
        if m.has_error:
            e = first(o for o in m.output if o.get('output_type')=='error')
            ln = f'{m.id}: {e["ename"]}: {e["evalue"]}'.replace('\n', '¶')
        else: ln = f'{m.id}: ok'
        return ln if len(ln)<=maxlen else ln[:maxlen-1]+'…'
    def show(self,
        maxlen:int=MAXLEN, # Maximum characters per status line
        rows:int=20, # Max ok lines shown in full (None: all); the rest collapse into a counted marker
    ):
        "One status line per message run, a collapsed marker for long ok stretches, and a final count line"
        idxs = list(range(len(self)))
        win = set(idxs if rows is None else idxs[:rows] if self.head else idxs[-rows:])
        out,elided = [],0
        for i,m in enumerate(self):
            if i in win or m.has_error:
                if elided: out.append(f'[...{elided} messages ok]')
                out.append(self._line(m, maxlen))
                elided = 0
            else: elided += 1
        if elided: out.append(f'[...{elided} messages ok]')
        fails = sum(m.has_error for m in self)
        n = len(self)-fails
        out.append(f'run: {n} msg{"s"*(n!=1)} ok'+(f', {fails} failed' if fails else ''))
        return PrettyString('\n'.join(out))

# %% ../nbs/01_dialog.ipynb #780d5344
@patch
@delegates(select_cells)
def execute(self:Dialog,
    *ids, # Message ids, or unique prefixes, to run; with `above`/`below`, the anchor; none, with no selection flags: run all
    shell=None, # `CaptureShell` to run in, kept for the caller; default is a fresh one, dropped at the end
    continue_on_error:bool=False, # Keep running after a failure?
    timeout:int=None, # Seconds before each message's run times out
    **kwargs
):
    "Run code messages on an execnb `CaptureShell`, capturing outputs into each message; `save` persists them"
    from execnb.shell import CaptureShell
    if not ids and not any(map(kwargs.get, ('above','below','all'))): kwargs['all'] = True
    sh = ifnone(shell, CaptureShell())
    res = []
    for m in select_cells(self, *ids, **kwargs):
        m.output = sh.run(m.source, timeout=timeout)
        res.append(m)
        if m.has_error and not continue_on_error: break
    return RunResult(res, head=kwargs.get('below', False))

# %% ../nbs/01_dialog.ipynb #4173c0fa
@patch
def execute(self:Message,
    shell=None, # `CaptureShell` to run in, kept for the caller; default is a fresh one, dropped at the end
    timeout:int=None, # Seconds before the run times out
):
    "Run this code message on an execnb `CaptureShell`, capturing outputs into it"
    return (self.dlg or Dialog([self])).execute(self.id, shell=shell, timeout=timeout)

# %% ../nbs/01_dialog.ipynb #103d7fb7
def _inline_atts(m, text):
    "Rewrite `attachment:` refs in `text` as data URIs from `m`'s attachments, making the Markdown self-contained"
    for a in m.attachments: text = text.replace(f'attachment:{a.id}', f'data:{a.content_type};base64,{base64.b64encode(a.data).decode()}')
    return text

def msg2md(m,
    weave:bool=False, # Code messages contribute only `render_text` over their outputs, as document prose?
):
    "One message as Markdown: notes verbatim with attachments inlined as data URIs, code in a ```python fence with outputs in a `::: output` div, prompts and replies in `::: prompt`/`::: reply` divs; None for empty code"
    if m.msg_type == snote: return _inline_atts(m, m.content)
    if m.msg_type == sraw: return fenced(m.content)
    if m.msg_type == sprompt:
        parts = [fenced(_inline_atts(m, m.content), ' prompt', ch=':')]
        if (ai := (m.ai_res or '')).strip(): parts.append(fenced(fmt_tools(ai), ' reply', ch=':'))
        return '\n\n'.join(parts)
    if weave: return render_text(m.output or []) or None
    if not m.content.strip(): return None
    parts = [fenced(m.content, 'python')]
    if (outs := render_md(m.output or [])): parts.append(fenced(outs, ' output', ch=':'))
    return '\n\n'.join(parts)

def dlg2md(d,
    exportfilter:bool=False, # Keep only the messages `export_filter` selects?
    weave:bool=False, # Code messages contribute only `render_text` over their outputs, as document prose?
):
    "The dialog as one Markdown document"
    ms = export_filter(d) if exportfilter else d
    return '\n\n'.join(filter(None, (msg2md(m, weave=weave) for m in ms))) + '\n'

# %% ../nbs/01_dialog.ipynb #0a922a21
def export_filter(ms):
    "The messages participating in an export: every exported one if any exist, else every non-pinned one"
    exp = [m for m in ms if m.exported]
    return exp if exp else [m for m in ms if not m.pinned]
