"""Message-level dialog diffing: what changed between two versions of a dialog, by id and facet

Anything that keeps a rendered or derived view of a dialog needs the same question answered when the dialog changes: which messages were added, removed, moved, or edited, and in what way? Messages carry stable ids, so identity is free and the diff is exact, no heuristic matching. `diff_dlgs(old, new)` returns a `DlgDiff` of added/removed/moved/changed, where `changed` records, per message, which facets differ (`content`, `output`, `meta`, `attachments`) along with each facet's old value, so a consumer can update only what a change actually touched. Volatile output fields (`execution_count`, `transient`) are ignored, so re-running a cell that produces the same result is not a change.

Docs: https://AnswerDotAI.github.io/aidialog/diff.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_diff.ipynb.

# %% auto #0
__all__ = ['DlgDiff', 'diff_dlgs']

# %% ../nbs/05_diff.ipynb #a40f7fb0
from dataclasses import dataclass
from difflib import SequenceMatcher
from fastcore.utils import *
from .dialog import Dialog, Message

# %% ../nbs/05_diff.ipynb #8e90a581
_volatile = ('execution_count','transient')

def _norm_out(o): return {k:v for k,v in o.items() if k not in _volatile}

def _facets(m):
    "Comparable snapshot of a message's semantic fields"
    out = m.output
    return dict(content=m.content,
                output=[_norm_out(o) for o in out] if isinstance(out,list) else out,
                meta=dict(m.meta),
                attachments=[(a.id,a.content_type,a.data) for a in m.attachments or []])

# %% ../nbs/05_diff.ipynb #5769c999
@dataclass
class DlgDiff:
    added: list    # (prev_id, Message) pairs, in new-dialog order
    removed: list  # Messages present in old but not new
    changed: dict  # id -> {facet: old value} for surviving messages
    moved: list    # (prev_id, id) pairs for surviving messages whose position changed
    def __bool__(self): return bool(self.added or self.removed or self.changed or self.moved)

# %% ../nbs/05_diff.ipynb #7244fc3d
def diff_dlgs(old, new):
    "Diff two dialogs (or message lists) into a `DlgDiff`; ids are assumed unique within each dialog"
    oms_l,nms_l = getattr(old,'messages',old), getattr(new,'messages',new)
    oms,nms = {m.id:m for m in oms_l}, {m.id:m for m in nms_l}
    removed = [m for m in oms_l if m.id not in nms]
    changed = {}
    for i in oms.keys() & nms.keys():
        of,nf = _facets(oms[i]),_facets(nms[i])
        if (d := {k:of[k] for k in of if of[k]!=nf[k]}): changed[i] = d
    oseq = [m.id for m in oms_l if m.id in nms]
    nseq = [m.id for m in nms_l if m.id in oms]
    stable = set()
    for blk in SequenceMatcher(a=oseq, b=nseq, autojunk=False).get_matching_blocks():
        stable.update(nseq[blk.b:blk.b+blk.size])
    order = [m.id for m in nms_l]
    def _prev(i):
        ix = order.index(i)
        return order[ix-1] if ix else None
    added = [(_prev(i), nms[i]) for i in order if i not in oms]
    moved = [(_prev(i), i) for i in nseq if i not in stable]
    return DlgDiff(added, removed, changed, moved)
