"""Converting dialogs into LLM chat history

Docs: https://AnswerDotAI.github.io/aidialog/hist.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_hist.ipynb.

# %% auto #0
__all__ = ['UNSUPPORTED_MSG', 'im_max', 'IMG_TOKS', 'expr_pat', 'expr_mtypes', 'jwrap', 'to_local_time', 'media_item',
           'resize_img', 'output_parts', 'merge_media', 'get_refs', 'sigil_pat', 'get_exprs', 'vars_tag', 'vars_hist',
           'is_nameerr', 'task_tags', 'warning_tag', 'dlg2hist', 'dlg2chat', 'chat2dlg', 'reply2dlg', 'dlg2reply']

# %% ../nbs/03_hist.ipynb #40ac6466
import re, ast, base64, binascii, hashlib
from ast import literal_eval
from datetime import datetime
from zoneinfo import ZoneInfo
from itertools import chain
from io import BytesIO

from fastcore.utils import *
from fastcore.xtras import detect_mime
from fastcore.nbio import item2xml, IMG_MIMES
from fastcore.xml import to_xml, Media, MediaUnavailable, Instructions, Prompt, Variable, Variables, System_reminder
from .msg_parts import MediaUrl, fmt2hist, hist2fmt, data_url, Msg, mk_tr_details, PartType, Part, mk_content
from .dialog import *

# %% ../nbs/03_hist.ipynb #b2c5d115
def jwrap(txts:list=['']):
    "Wrap plain `txt` in a minimal Jupyter-style cell output"
    return [dict(output_type='stream', name='stdout', text=txt) for txt in listify(txts)]

# %% ../nbs/03_hist.ipynb #6c897570
def to_local_time(time_str, tz='UTC'):
    "Convert ISO time string to local timezone"
    if not time_str: return ''
    try: dt = datetime.fromisoformat(time_str)
    except ValueError: return ''
    return dt.astimezone(ZoneInfo(tz)).isoformat()

@patch
def local_time(self:Message):
    "Localized `time_run` for hosts that stamp one; '' when absent"
    if not (t := getattr(self, 'time_run', '')): return ''
    tz = getattr(self.dlg, 'timezone', 'UTC') if self.dlg else 'UTC'
    return to_local_time(t, tz)

# %% ../nbs/03_hist.ipynb #dc9e55ab
def _mime_kind(mime):
    if mime == 'application/pdf': return 'pdf'
    return mime.split('/', 1)[0] if mime and mime.split('/', 1)[0] in {'image','audio','video'} else None

def _mime_supported(mime, aim_info):
    if   _mime_kind(mime) == 'image' and aim_info.get('supports_vision', False):      return True
    elif _mime_kind(mime) == 'video' and aim_info.get('supports_video_input', False): return True
    elif _mime_kind(mime) == 'audio' and aim_info.get('supports_audio_input', False): return True
    elif _mime_kind(mime) == 'pdf'   and aim_info.get('supports_pdf_input', False):   return True
    return False

# %% ../nbs/03_hist.ipynb #cab4286d
class _MissError(Exception): pass

UNSUPPORTED_MSG = "An unsupported media type was included in the context: {mime}. Please instruct the user to switch to a model that supports this media type."
Message.UNSUPPORTED_MSG = UNSUPPORTED_MSG

# %% ../nbs/03_hist.ipynb #8fde0964
def _media_xml(media_type, media_id, mime=None):
    "Create a media XML tag for LLM context."
    return to_xml(Media(id=media_id, type=media_type, mime=mime))

def _media_unavailable(media_type, media_id, e, mime=None):
    "Create a media-unavailable XML tag for LLM context."
    msg = "The user included this media, but it was not available to the AI. Tell the user that you cannot see it."
    return to_xml(MediaUnavailable(msg, id=str(media_id), type=media_type, reason=str(e), mime=mime))

def media_item(media_type, media_id, data, aim_info, mime=None, max_im_sz=None, prep=None, unavail_msg=UNSUPPORTED_MSG):
    "Load/prepare/package media, returning [xml_tag, data] or [media-unavailable]."
    try:
        # `data` can be bytes, or a function that loads bytes lazily.
        data = data() if callable(data) else data
        if data is None: raise _MissError("media data unavailable")
        if not isinstance(data, (bytes, MediaUrl)): raise _MissError(f"expected bytes or MediaUrl, got {type(data).__name__}")
        mime = mime or (detect_mime(data) if isinstance(data, bytes) else data.mime)
        if not mime: raise _MissError("unsupported or unknown media type")
        if not _mime_supported(mime, aim_info): raise _MissError(unavail_msg.format(mime=mime))
        # `media_id` can be a string, or a function that derives an id.
        media_id = media_id(data) if callable(media_id) else media_id
        if prep and isinstance(data, bytes): data = prep(data, mime, max_im_sz)
        return [_media_xml(media_type, media_id, mime), data]
    except (_MissError, OSError, binascii.Error) as e:
        media_id = getattr(media_id, '__name__', 'unknown') if callable(media_id) else media_id
        return [_media_unavailable(media_type, media_id, e, mime)]

# %% ../nbs/03_hist.ipynb #0fc50b6d
im_max = 768**2   # image-area budget for LLM context: OpenAI high detail = exactly 4 tiles; Anthropic ~786 toks
IMG_TOKS = 765    # assumed tokens per context image at `im_max`: OpenAI 85 base + 4*170 per tile

def resize_img(data:bytes, max_im_sz=im_max):
    "Resize `data` so that its area is <= `max_im_sz` total pixels; passthrough without pillow"
    try: from PIL import Image as PImg
    except ImportError: return data
    img = PImg.open(BytesIO(data))
    w,h = img.size
    if w*h <= max_im_sz: return data
    scale = (max_im_sz/(w*h))**0.5
    rw,rh = int(w*scale),int(h*scale)
    img_r = img.resize((rw, rh), PImg.Resampling.LANCZOS)
    img_b = BytesIO()
    img_r.save(img_b, format=img.format)
    return img_b.getvalue()

@patch
def prep_img(self:Message, data, mime, max_im_sz=None):
    "Resize raster images before they enter LLM context, so they don't consume too many tokens"
    return resize_img(data, max_im_sz or im_max) if mime in IMG_MIMES else data

# %% ../nbs/03_hist.ipynb #c9792733
def _media_atts(msg, aim_info, max_im_sz=None):
    "Build media context from a message's attachments that are referenced in the content."
    attids = set()
    attids.update(re.findall(r'!\[[^\]]*\]\(attachment:([0-9a-f-]{36})\)', msg.content))
    attids.update(re.findall(r'<!-- last_output:([0-9a-f-]{36}) -->', msg.content))
    atts = L(msg.attachments).filter(lambda o: o in sorted(attids))
    return list(chain.from_iterable(media_item('content', o.id, o.data, aim_info=aim_info, max_im_sz=max_im_sz,
        prep=msg.prep_img, unavail_msg=msg.UNSUPPORTED_MSG) for o in atts))

# %% ../nbs/03_hist.ipynb #91cbca46
def _img_id(im_bytes):
    "Generate a deterministic 8 char id from `im_bytes`"
    h = hashlib.md5(im_bytes)
    return base64.b32encode(h.digest()).decode('utf-8')[:8]

# %% ../nbs/03_hist.ipynb #08035646
def _img_item(pair, m, aim_info, max_im_sz):
    mime,data = pair
    return media_item('output', _img_id, partial(base64.b64decode, data), aim_info, mime, max_im_sz, prep=m.prep_img, unavail_msg=m.UNSUPPORTED_MSG)

def _out_img(data):
    "Preferred `(mime, b64)` image entry of mimebundle `data`, or None"
    return first((m, data[m]) for m in IMG_MIMES if m in data)

def _img_output(m, aim_info, max_im_sz):
    "Extract image outputs from `m` as encoded images and their xml tags, at most one image per output"
    pairs = L(m.output or []).attrgot('data', {}).map(_out_img).filter()
    return pairs.flatmap(_img_item, m=m, aim_info=aim_info, max_im_sz=max_im_sz)

# %% ../nbs/03_hist.ipynb #716d50cf
def output_parts(m, aim_info=None, max_im_sz=None):
    "Media `Part`s for a code message's outputs: gated, resized, id-tagged, with unavailable fallbacks; images enabled if `aim_info` is None"
    if aim_info is None: aim_info = dict(supports_vision=True)
    return [mk_content(o) for o in _img_output(m, aim_info, max_im_sz)]

def merge_media(text, parts):
    "Compose rendered `text` with media `parts`: media first (tag adjacency kept), text last; with no images, notes fold into the text"
    has_img = any(p.type==PartType.input_image for p in parts)
    if not has_img: return '\n\n'.join(filter(None, [text, *(p.text for p in parts)]))
    return [*parts, *([Part(type=PartType.text, text=text)] if text else [])]

# %% ../nbs/03_hist.ipynb #1e8a1f1b
@patch
def media_path(self:Dialog, ref):
    "Resolve a non-URL `#ai` media ref to a local path; hosts patch this to add their own roots and safety rules"
    p = Path(ref)
    if not p.is_absolute() and (pth := getattr(self, 'path_', None)): p = Path(pth).parent/p
    return p.resolve()

def _mk_media_tag(ref, msg, aim_info, max_im_sz=None):
    "Media tag and bytes for a path, URL, or base64 `ref`; raster images resize via `Message.prep_img`"
    kw = dict(prep=msg.prep_img, unavail_msg=msg.UNSUPPORTED_MSG)
    if ref.startswith('data:'):
        meta,data = ref.split(',', 1)
        mime = meta.removeprefix('data:').split(';')[0]
        return media_item('content', data[:10], lambda: base64.b64decode(data), aim_info, mime, max_im_sz, **kw)
    data = lambda: MediaUrl(ref) if ref.startswith(('http://', 'https://')) else (msg.dlg.media_path(ref) if msg.dlg else Path(ref).resolve()).read_bytes()
    return media_item('content', ref, data, aim_info, max_im_sz=max_im_sz, **kw)

_static_pat = re.compile(r'!\[[^\]]*\]\(([^)#]+)#ai\)')
def _media_static(msg, aim_info, max_im_sz=None):
    "Media items for `#ai`-tagged markdown links in `msg.content`"
    if '#ai' not in msg.content: return []
    return list(chain.from_iterable(_mk_media_tag(ref, msg, aim_info, max_im_sz) for ref in _static_pat.findall(msg.content)))

# %% ../nbs/03_hist.ipynb #909e346f
def get_refs(cts, sigil='&'):
    'Return sorted unique names referenced via sigil`name` or sigil`[name, name]` pattern in msgs'
    ms = re.findall(rf'{re.escape(sigil)}`([\w.]+|\[[\w.,\s]+\])`', cts)
    if not ms: return None
    return sorted(set(t.strip() for m in ms for t in re.split(r'[,\[\]]', m) if t.strip()))

# %% ../nbs/03_hist.ipynb #0dc6b6ef
def sigil_pat(sigil):
    "Regex for sigil`payload` refs, e.g. $`expr` or !`cmd`"
    return re.compile(rf'{re.escape(sigil)}`([^`]+)`')

expr_pat = sigil_pat('$')
expr_mtypes = ('prompt',)
def get_exprs(msgs, sigil='$'):
    "Sorted unique refs of `sigil` form found in prompt messages of `msgs`"
    cts = ' '.join((m.content or '') for m in msgs if m.msg_type in expr_mtypes)
    return sorted(set(sigil_pat(sigil).findall(cts)))


# %% ../nbs/03_hist.ipynb #59f960fd
def vars_tag(aim_info, ns=None):
    "<Variables> element and byte variables for this message"
    if not ns: return {}
    lead = f"The 'variables' section provides values of: {', '.join(v if v.startswith(('$`','!`')) else f'$`{v}`' for v in ns)}"
    vs,vimgs = [],[]
    for k,v in ns.items():
        if mime := detect_mime(v): vimgs.extend(media_item('variable', k, v, aim_info, mime))
        else: vs.append(Variable(v, name=k, type=type(v).__name__))
    vs = Variables(lead, *vs) if vs else None
    return dict(vars_tag=vs, vars_bytes=vimgs)

# %% ../nbs/03_hist.ipynb #77d21053
def vars_hist(aim_info, ns=None):
    "Single history turn holding all variable values, to sit above everything else"
    vt = vars_tag(aim_info, ns)
    if not vt: return []
    parts = []
    if vt.get('vars_tag'): parts.append(to_xml(vt['vars_tag'], do_escape=False))
    if vt.get('vars_bytes'): parts.extend(vt['vars_bytes'])
    if not parts: return []
    return [parts, 'Understood, I will use these variable values.']

# %% ../nbs/03_hist.ipynb #32a32f0c
def is_nameerr(v):
    "Does an `eval_exprs` result mark an undefined name?"
    return isinstance(v, str) and v.startswith('<error type="NameError"')

# %% ../nbs/03_hist.ipynb #38b8eeea
def task_tags(task: str, sid=None, time=None, tz='UTC'):
    "Envelope elements for a prompt: `<instructions>` plus `<prompt>` carrying `sid` and local run time"
    kw = {'sid':sid} if sid else {}
    if time: kw['time'] = to_local_time(time, tz)
    return Instructions('Respond to the request in the `prompt` below.'), Prompt(task, **kw)

def warning_tag(warning: str): return System_reminder('**NB**: ' + warning) if warning else None

# %% ../nbs/03_hist.ipynb #601875c5
@patch
def prompt_txt(self:Message, last=False):
    "History text for a prompt: the envelope (`last`, threaded by `dlg2hist`, is unused: the envelope is the same for every prompt)"
    tz = getattr(self.dlg, 'timezone', 'UTC') if self.dlg else 'UTC'
    instr,task = task_tags(self.content, self.id, getattr(self, 'time_run', None), tz)
    return to_xml(instr, do_escape=False) + '\n' + to_xml(task, do_escape=False)

@patch
def hist_xml(self:Message, last=False):
    "History XML for this message (the concise `Message.to_xml` is dlgskill's converter; this rendering adds time and serves `to_parts`)"
    if self.msg_type == sprompt: return self.prompt_txt(last)
    it = item2xml('markdown' if self.msg_type==snote else self.msg_type, self.content, self.ai_output,
                  id=self.id, time=self.local_time() or None, meta=self.meta)
    return to_xml(it, do_escape=False)

# %% ../nbs/03_hist.ipynb #e0542c55
@patch
def media_extra(self:Message, aim_info, max_im_sz=None):
    "Extra media sources beyond attachments and outputs: `#ai`-tagged markdown links by default; hosts patch to add more"
    return _media_static(self, aim_info, max_im_sz)

@patch
def to_media(self:Message, aim_info, max_im_sz=None):
    "Aggregate media from attachments, `media_extra`, and code outputs"
    media_ctx = []
    if media_atts := _media_atts(self, aim_info, max_im_sz): media_ctx += media_atts
    if extra := self.media_extra(aim_info, max_im_sz): media_ctx += extra
    if self.msg_type == scode:
        if img_outputs := _img_output(self, aim_info, max_im_sz): media_ctx += img_outputs
    return media_ctx

# %% ../nbs/03_hist.ipynb #afd617d8
@patch
def to_parts(self:Message, aim_info:dict, last=False):
    "Convert message to a list of history parts: media, then XML text."
    parts = []
    if media := self.to_media(aim_info): parts.extend(media)
    if mxml := self.hist_xml(last): parts.append(mxml)
    return parts

# %% ../nbs/03_hist.ipynb #0b6318f6
def dlg2hist(
    dlg, # A `Dialog`, or iterable of messages, ending with a prompt
    aim_info:dict, # Model capability dict for media handling
):
    "Convert `dlg` to LLM history. The final prompt renders with `last=True`."
    msgs = dlg.messages if isinstance(dlg, Dialog) else list(dlg)
    msgs = [m for m in msgs if not (m.msg_type==sraw and m.meta.get('rec_kind'))]  # tagged raws are session bookkeeping, not conversation
    msgs = [m for m in msgs if not m.skipped]  # `skipped` messages are hidden from the AI (solveit semantics)
    if msgs[-1].msg_type != sprompt: raise ValueError("dlg2hist requires the messages to end with a prompt")
    res = []
    for is_first, m in loop_first(reversed(msgs)):
        if m.msg_type == sprompt: res += [m.ai_output, m.to_parts(aim_info, last=is_first)]
        else: res[-1] = m.to_parts(aim_info) + res[-1]
    return res[::-1]

# %% ../nbs/03_hist.ipynb #22d1bb97
def _explode(a, t):
    "One call/result pair per tool use in a batched assistant/tool pair"
    tus = [p for p in a.content if p.type==PartType.tool_use]
    if len(tus)<2: return [a,t]
    pre,trs = [p for p in a.content if p.type!=PartType.tool_use],{p.data['id']:p for p in t.content}
    res = []
    for is_first,tu in loop_first(tus):
        res += [Msg(role='assistant', content=(pre if is_first else [])+[tu]), Msg(role='tool', content=[trs[tu.data['id']]])]
    return res

def _seq_tools(msgs):
    "Explode batched tool calls into strict call/result alternation"
    out = []
    for m in msgs:
        if m.role=='tool' and out and out[-1].role=='assistant': out += _explode(out.pop(), m)
        else: out.append(m)
    return out

# %% ../nbs/03_hist.ipynb #4eccdf09
def dlg2chat(
    dlg, # A `Dialog`, ending with a prompt
    aim_info=None, # Model capability dict for media handling; images enabled if None
):
    "Canonical chat messages for `dlg`, with each reply's tool calls recovered as real parts"
    hist = dlg2hist(dlg, dict(supports_vision=True) if aim_info is None else aim_info)
    msgs = []
    for i,t in enumerate(hist):
        if i%2==0: msgs.append(Msg('user', [mk_content(o) for o in t]))
        else: msgs += _seq_tools(fmt2hist(t))
    ids = [p.data['id'] for m in msgs for p in m.content if p.type==PartType.tool_use]
    if dups := {i for i in ids if ids.count(i)>1}: raise ValueError(f"duplicate tool call id(s): {', '.join(sorted(dups))}")
    return msgs

# %% ../nbs/03_hist.ipynb #11b036f3
_env_pat = re.compile(r'<instructions>.*?</instructions>\n<prompt(?: sid="(?P<sid>[^"]*)")?(?: time="[^"]*")?>(?P<task>.*)</prompt>$', re.S)
def chat2dlg(
    msgs, # Canonical messages, e.g. from `dlg2chat`
    name, # Dialog name
    cls=Dialog, # Dialog class to create
    mx=2000, # Maximum characters per rendered tool input/output string; None disables truncation (see `hist2fmt`)
):
    "A dialog for `msgs`: one prompt per user turn, replies rendered in the format `fmt2hist` parses"
    dlg,turns = cls(name=name),[]
    for m in msgs:
        if m.role=='user': turns.append((m,[]))
        elif turns: turns[-1][1].append(m)
        else: raise ValueError('msgs must start with a user message')
    for u,replies in turns:
        segs,atts = [],[]
        for p in u.content:
            if p.type==PartType.text: segs.append(p.text)
            elif p.type==PartType.input_image:
                mime,data = data_url(p.text)
                atts.append(Attachment(base64.b64decode(data), mime))
                segs.append(f'![](attachment:{atts[-1].id})')
            else: raise ValueError(f'unsupported user part: {p.type}')
        kw = {}
        if segs and (mt := _env_pat.search(segs[-1])):
            segs[-1] = segs[-1][:mt.start()] + mt['task']
            if mt['sid']: kw['id'] = mt['sid']
        dlg.mk_message('\n\n'.join(segs), msg_type=sprompt, output=hist2fmt(replies, mx=mx), attachments=atts, **kw)
    return dlg

# %% ../nbs/03_hist.ipynb #91b80931
def _dotted_name(s): return bool(s) and all(p.isidentifier() for p in s.split('.'))
def reply2dlg(pmsg):
    "Explode `pmsg`'s AI reply into a `Dialog` of note and code messages"
    sub = Dialog(name=pmsg.id)
    sub.msg_cls = type(pmsg)
    msgs = fmt2hist(pmsg.ai_res)
    trs = {p.data['id']:p for m in msgs if m.role=='tool' for p in m.content}
    for m in msgs:
        if m.role=='tool': continue
        for p in m.content:
            if p.type==PartType.tool_use:
                d = p.data
                if not _dotted_name(d['name']): raise ValueError(f"not a dotted Python identifier: {d['name']}")
                if bad := first(k for k in d['arguments'] if not k.isidentifier()): raise ValueError(f"not a Python identifier: {bad}")
                args = ', '.join(f'{k}={v!r}' for k,v in d['arguments'].items())
                sub.mk_message(f"{d['name']}({args})", output=code_output(trs[d['id']].text), meta=dict(tool_id=d['id']))
            elif p.type==PartType.text and p.text: sub.mk_message(p.text, msg_type=snote)
    return sub

# %% ../nbs/03_hist.ipynb #980f65be
def _parse_call(src):
    "`(name, arguments)` parsed from literal call source `src`, or None if it isn't one"
    try: call = ast.parse(src.strip(), mode='eval').body
    except SyntaxError: return None
    if not (isinstance(call, ast.Call) and not call.args and all(kw.arg for kw in call.keywords)): return None
    name = ast.unparse(call.func)
    if not _dotted_name(name): return None
    return name, {kw.arg: literal_eval(kw.value) for kw in call.keywords}

def _msg2tr(m):
    "Tool-result `Part` recovered from code message `m`, whose source is the literal call"
    if (p := _parse_call(m.content)) is None: raise ValueError(f"not a keyword-only tool call: {m.content!r}")
    tid = m.meta.setdefault('tool_id', 'call_'+rtoken_hex(8))
    return Part(type=PartType.tool_result, text=render_outputs_ai(m.output or []), data=dict(id=tid, name=p[0], arguments=p[1]))

def dlg2reply(sub):
    "Implode a sub-dialog of note and code messages back into reply markdown"
    parts = [mk_tr_details(_msg2tr(m), mx=None).strip() if m.msg_type==scode else m.content.strip() for m in sub.messages]
    return '\n\n'.join(p for p in parts if p)

# %% ../nbs/03_hist.ipynb #d654af4d
@patch(as_prop=True)
def tool_call(self:Message):
    "Parsed `dict(name=..., arguments=...)` when this code message's source is a literal tool call, else None"
    if self.msg_type != scode: return None
    if (p := _parse_call(self.content)) is None: return None
    return dict(name=p[0], arguments=p[1])
