"""Reading and writing dialogs as Jupyter notebooks

Docs: https://AnswerDotAI.github.io/aidialog/ipynb.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_ipynb.ipynb.

# %% auto #0
__all__ = ['CUR_VER', 'att2dict', 'home_atts', 'unhome_atts', 'conv_old_prompts', 'nb_ver', 'migrate_nb', 'get_ipynb',
           'safe_mtime', 'write_ipynb', 'ipynb_cells', 'dict2att', 'reads_ipynb', 'read_ipynb']

# %% ../nbs/02_ipynb.ipynb #d3d0463b
from fastcore.utils import *
from fastcore.xtras import atomic_save
from fastcore.nbio import mk_cell,new_nb,dict2nb,read_nb,nb2str,repair_cell,repair_nb
import json
from contextlib import suppress
from base64 import b64encode,b64decode
from .dialog import *
from .msg_parts import conv_tools

# %% ../nbs/02_ipynb.ipynb #aaaeb85a
def att2dict(att): return {att.content_type: b64encode(att.data).decode('ascii') if isinstance(att.data, bytes) else att.data}

# %% ../nbs/02_ipynb.ipynb #4687142c
def home_atts(nb):
    "Move code cells' attachments into the notebook-metadata home rustygate uses"
    home = nb['metadata'].setdefault('attachments', {})
    for c in nb['cells']:
        if c['cell_type']=='code' and (atts := c.pop('attachments', None)): home[c['id']] = atts
    if not home: nb['metadata'].pop('attachments', None)
    return nb

def unhome_atts(nb):
    "Reattach homed attachments onto their code cells: the inverse of `home_atts`"
    home = nb['metadata'].pop('attachments', {})
    for c in nb['cells']:
        if (atts := home.get(c['id'])): c['attachments'] = atts
    return nb

# %% ../nbs/02_ipynb.ipynb #58354f4a
_out_meta_skip = {'__type'}

def _clean_out_meta(o):
    "A copy of output `o` without transient metadata; never mutates the live output"
    o = dict(o)
    if m := o.get('metadata'): o['metadata'] = {k:v for k,v in m.items() if k not in _out_meta_skip}
    return o

# %% ../nbs/02_ipynb.ipynb #20f31fdc
@patch
def cell_meta(self:Message):
    "Metadata dict to write: `meta` plus demoted `meta_attrs` fields, falsy values omitted"
    meta = dict(self.meta)
    for a,k in self.meta_attrs.items():
        if (v := getattr(self, a, None)): meta[k] = v
        else: meta.pop(k, None)
    return meta

# %% ../nbs/02_ipynb.ipynb #0dde746d
_prompt_magic = '%%prompt'

@patch
def to_cell(self:Message):
    "Convert message to a notebook cell"
    meta = self.cell_meta()
    src = self.source
    if self.msg_type==sprompt:
        meta['solveit_ai'] = True
        src = f'{_prompt_magic}\n{src}'
    outkw = {}
    if self.msg_type in (scode,sprompt) and self.output: outkw['outputs'] = [_clean_out_meta(o) for o in self.output]
    atts = {att.id: att2dict(att) for att in (self.attachments or [])}
    if atts: outkw['attachments'] = atts
    cell = mk_cell(src, self.cell_type, id=self.id, metadata=meta, **outkw)
    if repairs := repair_cell(cell): print('NB repair:', '; '.join(repairs))
    return cell

# %% ../nbs/02_ipynb.ipynb #ded8e1b4
_reply_sep = "\n\n##### 🤖Reply🤖<!-- SOLVEIT_SEPARATOR_7f3a9b2c -->\n\n"

def conv_old_prompts(nb):
    "Rewrite old markdown-form prompt cells to the code-cell form, in place; returns the changed cell ids"
    changed = []
    for c in nb['cells']:
        if c['cell_type']!='markdown' or not c['metadata'].get('solveit_ai'): continue
        if isinstance(c['source'], list): c['source'] = ''.join(c['source'])
        content,*reply = c['source'].split(_reply_sep)
        c['cell_type'] = 'code'
        c['source'] = f'{_prompt_magic}\n{content}'
        c['outputs'] = prompt_output(reply[0]) if reply else []
        c['execution_count'] = None
        changed.append(c['id'])
    if changed: home_atts(nb)
    return changed

# %% ../nbs/02_ipynb.ipynb #migrations
CUR_VER = 3

def nb_ver(nb):
    "Stored notebook version; unversioned files start at v1"
    meta = nb.get('metadata', {})
    return meta.get('solveit', {}).get('ver', meta.get('solveit_ver', 1))

# %% ../nbs/02_ipynb.ipynb #migratev1
def _v1_to_v2(nb):
    meta = nb.setdefault('metadata', {})
    sv = meta.get('solveit', {})
    modes = {1:'standard', 2:'learning', 3:'concise'}
    if isinstance(sv.get('mode'), int): sv['mode'] = modes[sv['mode']]
    if isinstance(meta.get('solveit_dialog_mode'), int): meta['solveit_dialog_mode'] = modes[meta['solveit_dialog_mode']]

# %% ../nbs/02_ipynb.ipynb #migratev2
def _v2_to_v3(nb):
    meta = nb.setdefault('metadata', {})
    sv = meta.setdefault('solveit', {})
    if 'solveit_dialog_mode' in meta: sv.setdefault('mode', meta.pop('solveit_dialog_mode'))
    meta.pop('solveit_ver', None)
    conv_old_prompts(nb)
    for c in nb['cells']:
        if not c['metadata'].get('solveit_ai'): continue
        for o in c.get('outputs', []):
            md = nested_idx(o, 'metadata', 'is_ai_res') and nested_idx(o, 'data', 'text/markdown')
            if not md: continue
            if '-usage-details' in md: o['data']['text/markdown'] = conv_tools(md)

# %% ../nbs/02_ipynb.ipynb #migratenb
_migrations = {1:_v1_to_v2, 2:_v2_to_v3}

def migrate_nb(nb):
    "Upgrade a normalized notebook in place. Return whether its version changed"
    ver = nb_ver(nb)
    if not 1 <= ver <= CUR_VER: raise ValueError(f'Unsupported notebook version: {ver}')
    for v in range(ver, CUR_VER):
        _migrations[v](nb)
        nb.setdefault('metadata', {}).setdefault('solveit', {})['ver'] = v+1
    return ver < CUR_VER

# %% ../nbs/02_ipynb.ipynb #10a73cfc
def get_ipynb(dlg:Dialog, msgs=None):
    "Notebook object for `dlg`; `msgs` defaults to all its messages"
    cells = [m.to_cell() for m in (dlg.messages if msgs is None else msgs)]
    meta = dict(dlg.meta)
    meta['solveit'] = dict(meta.get('solveit', {}), ver=CUR_VER)
    nb = new_nb(cells=cells, meta=meta)
    home_atts(nb)
    if repairs := repair_nb(nb): print('NB repair:', '; '.join(repairs))
    return nb


# %% ../nbs/02_ipynb.ipynb #8fa39210
def safe_mtime(p):
    "mtime of `p`, its symlink if the target is missing, or None if `p` vanished (e.g. an atomic-save temp file)"
    with suppress(FileNotFoundError): return p.stat().st_mtime
    with suppress(FileNotFoundError): return p.stat(follow_symlinks=False).st_mtime

# %% ../nbs/02_ipynb.ipynb #ea5fa1dd
def write_ipynb(dlg:Dialog, fname=None, msgs=None, **kwargs):
    "Write `dlg` as a notebook, or return the JSON string if `fname` is None; `kwargs` (e.g. `uid`/`gid`) pass to `atomic_save`"
    res = nb2str(get_ipynb(dlg, msgs=msgs))
    if not fname: return res
    fname = Path(fname).expanduser()
    with atomic_save(fname, mode='w', encoding='utf-8', **kwargs) as f: f.write(res)
    dlg.mtime_ = safe_mtime(fname)
    dlg.migrated_ = False

# %% ../nbs/02_ipynb.ipynb #5527e596
@patch
def write(self:Dialog, base_path, msgs=None, **kwargs):
    write_ipynb(self, Path(base_path).expanduser()/f'{self.name}.ipynb', msgs=msgs, **kwargs)

# %% ../nbs/02_ipynb.ipynb #0e16e93a
def ipynb_cells(path, nm, prefix=None, suffix=None):
    tmpl = Path(path).expanduser()/f'{nm}.ipynb'
    if not tmpl.exists(): return []
    try: nb = read_nb(tmpl)
    except json.JSONDecodeError: return []
    if repairs := repair_nb(nb): print('NB repair:', '; '.join(repairs))
    migrate_nb(nb)
    unhome_atts(nb)
    return listify(prefix) + nb.cells + listify(suffix)

# %% ../nbs/02_ipynb.ipynb #ba0bb61e
def dict2att(att_id, att_data):
    "Convert attachment dict to Attachment object"
    content_type, data = first(att_data.items())
    if isinstance(data, str): data = b64decode(data)
    return Attachment(data, content_type, att_id)

def _output_from_cell(cell):
    if cell.cell_type!='code': return ''
    return getattr(cell, 'outputs', [])

# %% ../nbs/02_ipynb.ipynb #1b43e94f
@patch
def cell2msg(self:Dialog, cell):
    "Convert single notebook cell to message object"
    meta = dict(cell.metadata)
    kwargs = {a: meta.pop(k) for a,k in self.msg_cls.meta_attrs.items() if k in meta}
    content = cell.get('source', '')
    msg_type = sprompt if meta.pop('solveit_ai', 0) else snote if cell.cell_type=='markdown' else cell.cell_type
    if msg_type==sprompt and content.split('\n', 1)[0].strip()==_prompt_magic:
        content = content.split('\n', 1)[1] if '\n' in content else ''
    output = '' if msg_type in (snote,sraw) else _output_from_cell(cell)
    atts = [dict2att(att_id, att_data) for att_id, att_data in cell.get('attachments', {}).items()]
    id = getattr(cell, 'id', None) or rtoken_hex(4)
    return self.msg_cls(content, id=id, output=output, msg_type=msg_type, dlg=self, attachments=atts, meta=meta, **kwargs)

# %% ../nbs/02_ipynb.ipynb #aef05275
@patch
def from_cells(self:Dialog, cells):
    self.messages = Msgs(cells).map(self.cell2msg)
    return self

# %% ../nbs/02_ipynb.ipynb #6bdaa293
def reads_ipynb(txt, cls=Dialog, name='dialog', verbose=False):
    "Read a dialog from notebook JSON string `txt`, constructing via `cls`"
    nb = json.loads(txt)
    if (repairs := repair_nb(nb)) and verbose: print('NB repair:', '; '.join(repairs))
    unhome_atts(nb)
    nb = dict2nb(nb)
    migrated = migrate_nb(nb)
    unhome_atts(nb)
    res = cls(name=name, meta=dict(nb.get('metadata', {}))).from_cells(nb.cells)
    res.migrated_ = migrated
    return res

# %% ../nbs/02_ipynb.ipynb #7e8912e8
def read_ipynb(fname, cls=Dialog, name=None, verbose=False):
    "Read a dialog from notebook file `fname` (`.ipynb` added if missing), constructing via `cls`; `name` defaults to the file stem"
    f = Path(fname).expanduser()
    if f.suffix != '.ipynb': f = f.with_suffix('.ipynb')
    if not f.exists(): return print(f,'does not exist')
    try: res = reads_ipynb(f.read_text(encoding='utf-8'), cls, name or f.stem, verbose=verbose)
    except (json.JSONDecodeError, PermissionError): return
    res.path_ = f
    res.mtime_ = safe_mtime(f)
    return res

# %% ../nbs/02_ipynb.ipynb #87786976
@patch
def save(self:Dialog, fname=None):
    "Write back to `fname`, or to the `path_` stamped by `read_ipynb`"
    fname = fname or self.path_
    if not fname: raise ValueError('no fname passed, and no `path_` stamped by read_ipynb')
    write_ipynb(self, fname)
