"""The canonical LLM message model - `Msg` and the `Part` classes - and its formatted text form

Docs: https://AnswerDotAI.github.io/aidialog/msg_parts.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_msg_parts.ipynb.

# %% auto #0
__all__ = ['PartType', 'tool_info', 'usage_info', 'think_start', 'think_end', 're_think', 'fence_call_re', 'Part', 'Text',
           'Thinking', 'Refusal', 'Media', 'InputImage', 'InputAudio', 'InputVideo', 'InputFile', 'mk_part', 'Msg',
           'ToolUse', 'ToolResult', 'ServerToolResult', 'display_list', 'Completion', 'mk_tool_res_msg', 'sys_text',
           'part_txt', 'data_url', 'url_mime', 'MediaUrl', 'mk_content', 'parse_tools', 'strip_tools', 'conv_tools',
           'extract_fence_call', 'mk_result_fence', 'split_fence_msgs', 'tool_text', 'fmt2hist', 'ToolResponse',
           'StopResponse', 'FullResponse', 'trunc_str', 'mk_tr_details', 'hist2fmt', 'mk_msg', 'mk_msgs']

# %% ../nbs/00_msg_parts.ipynb #a616b4f5
import base64, json, copy
from json import dumps
from fastcore.utils import *
from fastcore.xtras import detect_mime

# %% ../nbs/00_msg_parts.ipynb #2212704a
class Part(BasicRepr):
    "Base class for content parts; subclasses register under the wire tag they serialize as."
    text = None    # subclasses that carry text declare it as an attribute; the rest read as None
    reg = {}       # wire tag -> subclass
    def __init__(self,
        *,
        raw=None,          # The vendor's original block, kept for lossless round-trips
        cache_control=None # Prompt-cache directive for providers that take one
    ):
        store_attr()
    def __init_subclass__(cls, tag=None, **kw):
        super().__init_subclass__(**kw)
        if tag: cls.type,Part.reg[tag] = tag,cls
    def __eq__(self, o): return type(o) is type(self) and self.__dict__ == o.__dict__
    def __hash__(self): return hash((type(self).__name__, self.text))
    def replace(self, **kw):
        "A copy of this part with `kw` attributes changed"
        res = copy.copy(self)
        res.__dict__.update(kw)
        return res

# %% ../nbs/00_msg_parts.ipynb #5342db55
PartType = str_enum('PartType', 'text', 'thinking', 'refusal', 'tool_use', 'server_tool_result', 'tool_result',
                    'input_image', 'input_audio', 'input_video', 'input_file')

# %% ../nbs/00_msg_parts.ipynb #48496c08
class Text(Part, tag=PartType.text):
    "Plain text content."
    def __init__(self, text=None, citations=None, **kw):
        super().__init__(**kw)
        store_attr('text,citations')

class Thinking(Part, tag=PartType.thinking):
    "A reasoning block; `showthink` asks renderers to show the thought rather than a 🧠 glyph."
    def __init__(self, text=None, showthink=False, **kw):
        super().__init__(**kw)
        store_attr('text,showthink')

class Refusal(Part, tag=PartType.refusal):
    "A provider's refusal to answer."
    def __init__(self, text=None, **kw):
        super().__init__(**kw)
        store_attr('text')

class Media(Part):
    "Media content: `text` is a URL or data URL."
    def __init__(self, text=None, mime=None, **kw):
        super().__init__(**kw)
        store_attr('text,mime')

class InputImage(Media, tag=PartType.input_image): "An image input."
class InputAudio(Media, tag=PartType.input_audio): "An audio input."
class InputVideo(Media, tag=PartType.input_video): "A video input."
class InputFile (Media, tag=PartType.input_file ): "A file input."

def mk_part(type, **kw):
    "The `Part` subclass registered for wire tag `type`, built from `kw`"
    return Part.reg[type](**kw)

# %% ../nbs/00_msg_parts.ipynb #026bfff6
def _trunc_strs(o, n=200):
    "Truncate str or dict"
    if not o: return o
    if isinstance(o,str) and len(o)>n: return o[:100]+'...'
    if isinstance(o,dict): return {k: (v[:100]+'...' if isinstance(v,str) and len(v)>n else v) for k,v in o.items()}
    return o

@patch
def _repr_markdown_(self:Part):
    flds = '\n'.join(f"- {k}: `{_trunc_strs(getattr(self,k))}`" for k in self.__stored_args__ if k not in ('text','cache_control'))
    return f"""**{type(self).__name__}** (`{self.type}`)

{_trunc_strs(self.text) if self.text else ''}

::: details

{flds}

:::"""

# %% ../nbs/00_msg_parts.ipynb #ae349c18
class Msg(BasicRepr):
    "A normalized message."
    def __init__(self,
        role,   # 'user', 'assistant', or 'tool'
        content # list of `Part`
    ):
        store_attr()

    @property
    def text(self): return ''.join(p.text or '' for p in self.content if isinstance(p, Text))

    def __eq__(self, o): return type(o) is type(self) and self.__dict__ == o.__dict__
    def __hash__(self): return hash((self.role, len(self.content)))

    def _repr_markdown_(self):
        return f"""**Msg**

- role: `{self.role}`

<contents>

{'\n\n'.join(p._repr_markdown_() for p in self.content)}

</contents>"""

# %% ../nbs/00_msg_parts.ipynb #3cbac5be
class _ToolPart(Part):
    "Shared shape of a tool call and its result."
    def __init__(self, id=None, name=None, arguments=None, server=False, text=None, **kw):
        if arguments is None: arguments = {}
        super().__init__(**kw)
        store_attr('id,name,arguments,server,text')

class ToolUse  (_ToolPart, tag=PartType.tool_use   ): "A tool invocation; `server` marks one the provider ran itself."
class ToolResult(_ToolPart, tag=PartType.tool_result): "A tool call's result, `text` holding the output."
class ServerToolResult(Part, tag=PartType.server_tool_result):
    "A provider-side tool result, kept as `raw` for round-trips."
    def __init__(self, text=None, **kw):
        super().__init__(**kw)
        store_attr('text')

# %% ../nbs/00_msg_parts.ipynb #195b4d89
@patch
def _repr_markdown_(self:ToolUse):
    return f"""🔧 **{self.name}**(`{self.arguments}`)

::: details

- id: `{self.id}`
- server: `{self.server}`
- raw: `{_trunc_strs(self.raw)}`

:::"""

def display_list(l): 
    from IPython.display import Markdown, display
    display(Markdown('\n\n'.join(o._repr_markdown_() for o in l)))

# %% ../nbs/00_msg_parts.ipynb #0168c535
class Completion(BasicRepr):
    "Normalized completion response."
    def __init__(self, model, message, finish_reason=None, usage=None, api_name=None, vendor_name=None, raw=None):
        if raw is None: raw = {}
        store_attr()
    def __eq__(self, o): return type(o) is type(self) and self.__dict__ == o.__dict__
    def __hash__(self): return hash((self.model, self.finish_reason, self.api_name, self.vendor_name))

    @property
    def tool_calls(self):
        "The `ToolUse` parts of `message`: a call lives in the content, not beside it"
        return [p for p in self.message.content if isinstance(p, ToolUse)]

# %% ../nbs/00_msg_parts.ipynb #7c88fce1
def mk_tool_res_msg(tool_calls:list[ToolUse], results:list[str|list]):
    'A util to prepare parallel tool call with str or media list results'
    parts = [ToolResult(id=tc.id, name=tc.name, arguments=tc.arguments, server=tc.server, text=res)
             for tc,res in zip(tool_calls, results)]
    return Msg(role="tool", content=parts)

# %% ../nbs/00_msg_parts.ipynb #07b612b3
def sys_text(system):
    "Extract text from system (str or Part)."
    if system is None: return None
    return system if isinstance(system, str) else system.text

def part_txt(p): return p.text if isinstance(p,Part) else p

# %% ../nbs/00_msg_parts.ipynb #f30c7962
@flexicache(time_policy(24*3600))
def _fetch_url_partial(url, nbytes=512):
    "Fetch remote media, returning `(content_type_header, bytes)`; bytes optionally only the first `nbytes`."
    import httpx  # deliberately lazy: keeps aidialog's deps to fastcore alone (may re-base on fastcore.net later)
    try:
        with httpx.stream('GET', url, headers={'Range': f'bytes=0-{nbytes-1}'}, follow_redirects=True) as r:
            if r.status_code not in (200, 206): return None, None
            return r.headers.get('content-type'), r.read()
    except (httpx.HTTPError, httpx.InvalidURL): return None, None

# %% ../nbs/00_msg_parts.ipynb #b6f61273
_ext_mime = {
    '.jpg':'image/jpeg', '.jpeg':'image/jpeg', '.png':'image/png', '.gif':'image/gif', '.webp':'image/webp', '.svg':'image/svg+xml',
    '.pdf':'application/pdf',
    '.mp3':'audio/mpeg', '.wav':'audio/wav', '.ogg':'audio/ogg', '.flac':'audio/flac', '.m4a':'audio/mp4',
    '.mp4':'video/mp4', '.mov':'video/quicktime', '.webm':'video/webm',
}

def data_url(url):
    "Parse data:mime;base64,data URL into (mime, b64_data), or None."
    if not isinstance(url, str) or not url.startswith('data:') or ',' not in url: return None
    header, body = url.split(',', 1)
    if ';base64' not in header or not body: return None
    return header[5:].split(';',1)[0].strip() or 'application/octet-stream', body

def url_mime(url, default='application/octet-stream'):
    "Guess mime from URL extension, then the server's Content-Type, then sniffed bytes; never None."
    if "youtube.com" in url or "youtu.be" in url: return "video/mp4"
    ext = '.' + url.rsplit('.', 1)[-1].split('?')[0].lower() if '.' in url.split('?')[0].split('/')[-1] else ''
    if (mime:=_ext_mime.get(ext)) is None:
        ctype, data = _fetch_url_partial(url)
        mime = (ctype or '').split(';')[0].strip().lower()
        if not mime or mime in ('application/octet-stream', 'text/plain'): mime = detect_mime(data)  # generic headers say nothing
    return ifnone(mime, default)

# %% ../nbs/00_msg_parts.ipynb #189772f5
class MediaUrl(BasicRepr):
    "Direct URL media reference"
    def __init__(self, url, mime=None): self.url, self.mime = url, ifnone(mime, url_mime(url))

# %% ../nbs/00_msg_parts.ipynb #859905d7
def _mime2part_cls(mime):
    "The `Media` subclass for MIME string `mime`"
    if mime.startswith('image/'): return InputImage
    if mime.startswith('audio/'): return InputAudio
    if mime.startswith('video/'): return InputVideo
    return InputFile

def _bytes2content(data):
    "Convert bytes to fastllm canonical content"
    mtype = detect_mime(data)
    if not mtype: raise ValueError(f'Data must be a supported file type, got {data[:10]}')
    encoded = base64.b64encode(data).decode("utf-8")
    return _mime2part_cls(mtype)(f'data:{mtype};base64,{encoded}', mime=mtype)

def _url2content(o):
    "Convert MediaUrl to fastllm canonical content"
    mime = o.mime or url_mime(o.url)
    return _mime2part_cls(mime)(o.url, mime=mime)

def mk_content(o):
    "Convert a content value (str, bytes, `MediaUrl`, or already a `Part`) to a canonical `Part`"
    if isinstance(o, str):        return Text(o)
    elif isinstance(o, bytes):    return _bytes2content(o)
    elif isinstance(o, MediaUrl): return _url2content(o)
    return o

# %% ../nbs/00_msg_parts.ipynb #ee9c825e
tool_info = 'json {.tool}'     # fence info string of a tool block: {id, name, args, result} (+server; `error` reserved)
usage_info = 'json {.usage}'   # fence info string of a usage block: UsageStats fields

def parse_tools(s):
    "Split `s` into `(text, data)` segments: `data` is a parsed `{.tool}` block dict, `None` for the final segment"
    res, pos = [], 0
    for info,body,start,end in fenced_blocks(s):
        if info != tool_info: continue
        try: d = json.loads(body)
        except Exception: continue
        res.append((s[pos:start], d))
        pos = end
    return res + [(s[pos:], None)]

def strip_tools(s, tools=True, usage=True):
    "Remove `{.tool}` (and `{.usage}`) blocks from `s`"
    out, pos = [], 0
    for info,body,start,end in fenced_blocks(s):
        if not (tools and info == tool_info) and not (usage and info == usage_info): continue
        out.append(s[pos:start])
        pos = end
    out.append(s[pos:])
    return ''.join(out)

think_start,think_end = '<!--think_start-->','<!--think_end-->'
re_think = re.compile(rf'{re.escape(think_start)}.*?{re.escape(think_end)}\n?', re.DOTALL)

# Frozen legacy envelope recognition, used only by `conv_tools`. These are the
# exact patterns fastllm shipped for the released `<details markdown='1'>`
# envelopes plus the never-released `::: {.details}` spelling.
_lg_tool_tag = "<details class='tool-usage-details' markdown='1'>"
_lg_token_tag = "<details class='token-usage-details' markdown='1'>"
_lg_tool_attrs, _lg_token_attrs = "{.details .tool-usage-details}", "{.details .token-usage-details}"
_lg_tools = re.compile(
    fr"^(?:{_lg_tool_tag}\n*(?:<summary>(?P<summ1>.*?)</summary>\n*)?\n*```json\n+(?P<json1>.*?)\n+```\n+</details>"
    fr"|(?P<fence>:{{3,}}) {re.escape(_lg_tool_attrs)}\n+(?:## (?P<summ2>.*?)\n+)?```json\n+(?P<json2>.*?)\n+```\n+(?P=fence)$)",
    flags=re.DOTALL|re.MULTILINE)
_lg_token = re.compile(
    fr"^(?:{re.escape(_lg_token_tag)}\n*<summary>(?P<tsumm1>.*?)</summary>\n*\n*`(?P<trepr1>.*?)`\n*\n*</details>"
    fr"|(?P<tfence>:{{3,}}) {re.escape(_lg_token_attrs)}\n+## (?P<tsumm2>.*?)\n+`(?P<trepr2>.*?)`\n+(?P=tfence)$)\n?",
    flags=re.DOTALL|re.MULTILINE)

def conv_tools(s):
    "Convert legacy tool/usage envelopes in `s` (both historical spellings) to the fenced JSON wire format. Idempotent."
    def _tool(m):
        tj = m['json1'] if m['json1'] is not None else m['json2']
        try: d = json.loads(tj.strip())
        except Exception: return m[0]
        call = d.get('call') or {}
        res = dict(id=d.get('id'), name=call.get('function'), args=call.get('arguments') or {}, result=d.get('result'))
        if d.get('server'): res['server'] = True
        return fenced(dumps(res, indent=2, ensure_ascii=False), tool_info)
    def _tok(m):
        summ = m['tsumm1'] if m['tsumm1'] is not None else m['tsumm2']
        det = m['trepr1'] if m['trepr1'] is not None else m['trepr2']
        return fenced(dumps(dict(summary=summ, detail=det), ensure_ascii=False), usage_info)
    return _lg_token.sub(_tok, _lg_tools.sub(_tool, s))

# %% ../nbs/00_msg_parts.ipynb #7ae2959f
_fence_back = '`````'
_result_re = re.compile(f'\n{_fence_back}result\n(.*?)\n{_fence_back}\n', re.DOTALL)
fence_call_re = re.compile(f'^{_fence_back}(py|bash)\n(.*?)\n{_fence_back}$', re.DOTALL | re.MULTILINE)


# %% ../nbs/00_msg_parts.ipynb #52b27fdc
def extract_fence_call(text):
    "Return (lang, code) if text ends with terminated py/bash fence, else None"
    ms = list(fence_call_re.finditer(text))
    if not ms: return None
    m = ms[-1]
    if not text[m.end():].strip(): return m.group(1), m.group(2)

# %% ../nbs/00_msg_parts.ipynb #6d60c135
def mk_result_fence(output): return f"\n{_fence_back}result\n{output}\n{_fence_back}\n"

def _split_msg_on_fences(msg):
    "Split an assistant Msg on result fences, return list of Msgs"
    if msg.role != 'assistant': return [msg]
    if not _result_re.search(msg.text): return [msg]
    res, asst_parts, tool_parts = [], [], []
    for p in msg.content:
        if   isinstance(p, Thinking): asst_parts.append(p)
        elif isinstance(p, ToolUse):  tool_parts.append(p)
        elif parts := _result_re.split(p.text or ''):
            for i,o in enumerate(parts):
                if not o: continue
                if i % 2 == 0: res.append(Msg(role='assistant', content=asst_parts+[Text(o.strip())]))
                else:          res.append(Msg(role='user',      content=[Text(mk_result_fence(o))]))
    if tool_parts: res.append(Msg(role='assistant', content=tool_parts))
    return res

def split_fence_msgs(msgs):
    "Split all assistant msgs on result fences for wire protocol"
    res = []
    for m in msgs: res.extend(_split_msg_on_fences(m))
    return res

# %% ../nbs/00_msg_parts.ipynb #3f2a30e7
def _media_tag(p):
    m = getattr(p, 'mime', None)
    return f"<media {p.type} {m}>" if m else f"<media {p.type}>"

def tool_text(
    res, # A tool function's return value
):
    "Canonical string form of a tool result: `Part` lists render as text and `<media>` tags, dicts/lists as JSON, everything else via `str`"
    if isinstance(res, str): return res
    if isinstance(res, list) and all(isinstance(o, Part) for o in res): return '\n'.join(o.ctext for o in res)
    if isinstance(res, (dict, list)): return dumps(res, ensure_ascii=False, default=str)
    return str(res)

# %% ../nbs/00_msg_parts.ipynb #ade55a7b
def _extract_tool_parts(d:dict):
    "Build (tool_use_part, tool_result_part) from a parsed `{.tool}` block"
    # Skip server tool calls in deserialization (round trip issues with Gemini/Anthropic)
    if not d or d.get('server') or d.get('id') is None: return None
    tu = ToolUse   (id=d['id'], name=d['name'], arguments=d.get('args') or {})
    tr = ToolResult(id=d['id'], name=d['name'], text=tool_text(d.get('result')))
    return tu, tr

# %% ../nbs/00_msg_parts.ipynb #916f8df0
def fmt2hist(outp:str)->list[Msg]:
    "Transform a formatted output string into fastllm canonical Msgs"
    if usage_info in outp: outp = strip_tools(outp, tools=False)
    if think_start in outp: outp = re_think.sub('', outp)
    if tool_info not in outp:
        msg = Msg(role='assistant', content=[Text(outp.strip() or '.')])
        return _split_msg_on_fences(msg)
    hist, asst_parts, tool_parts = [], [], []
    def flush():
        if tool_parts:
            hist.append(Msg(role='assistant', content=asst_parts.copy()))
            hist.append(Msg(role='tool',      content=tool_parts.copy()))
            asst_parts.clear()
            tool_parts.clear()
    for txt,d in parse_tools(outp.strip()):
        if txt and txt.strip():
            if tool_parts: flush()
            asst_parts.append(Text(txt.strip() or '.'))
        if d and (tp := _extract_tool_parts(d)):
            asst_parts.append(tp[0])
            tool_parts.append(tp[1])
    flush()
    if asst_parts: hist.append(Msg(role='assistant', content=asst_parts))
    if not hist: hist.append(Msg(role='assistant', content=[Text('.')]))
    result = []
    for msg in hist:
        if msg.role == 'assistant': result.extend(_split_msg_on_fences(msg))
        else: result.append(msg)
    if result[-1].role == 'tool': result.append(Msg(role='assistant', content=[Text('.')]))
    return result

# %% ../nbs/00_msg_parts.ipynb #6fe280ec
class ToolResponse(BasicRepr):
    def __init__(self, content): store_attr()  # list of (text, result) pairs
    def __eq__(self, o): return type(o) is type(self) and self.__dict__ == o.__dict__
    def __hash__(self): return hash(str(self.content))

# %% ../nbs/00_msg_parts.ipynb #86265805
class StopResponse(str): pass
class FullResponse(str): pass

# %% ../nbs/00_msg_parts.ipynb #4f105e4d
def trunc_str(s, mx=2000, skip=10, replace="TRUNCATED"):
    "Truncate `s` to `mx` chars max, adding `replace` if truncated; `mx=None` disables truncation"
    if mx is None or isinstance_str(s, ('FullResponse','Safe','PrettyString')): return s
    if not isinstance(s, str): s = str(s)
    s = type(s)(s.rstrip())
    if len(s)>2 and s[0]=='𝍁' and s[-1]=='𝍁':
        s = s[1:-1]
        if replace: return s
    if mx is None or len(s)<=mx: return s
    s = s[skip:mx-skip]
    ss = s.split(' ')
    if len(ss[-1])>150: ss[-1] = ss[-1][:5]
    s = ' '.join(ss)
    if skip: s = f"…{s}"
    s = f"{s}…"
    if replace: s = f"<{replace}>{s}</{replace}>"
    return s

# %% ../nbs/00_msg_parts.ipynb #d7d00f19
def _trunc_param(v, mx=40):
    "Truncate and escape param value for display"
    tp = trunc_str(str(v).replace('`', r'\`'), mx=mx, replace=None, skip=0)
    try: return dumps(tp, ensure_ascii=False)
    except Exception: return repr(tp).replace('\\\\', '\\')

def _tc_summary(tr):
    "Format tool call as a `func(params)→result` code span"
    params = ', '.join(f"{k}={_trunc_param(v)}" for k,v in tr.arguments.items())
    res = f"→{_trunc_param(tr.text)}" if tr.text else ''
    txt = f"{tr.name}({params}){res}"
    ticks = '`'*(max(map(len, re.findall('`+', txt)), default=0)+1)
    pad = ' ' if '`' in txt else ''
    return f"{ticks}{pad}{txt}{pad}{ticks}"

# %% ../nbs/00_msg_parts.ipynb #f08c8cbd
def mk_tr_details(tr, mx=2000):
    "Create the `{.tool}` wire block for a tool call; `mx=None` disables truncation"
    args = {k:trunc_str(v, mx=None if mx is None else mx*5) if isinstance(v, str) else v for k,v in tr.arguments.items()}
    res = dict(id=tr.id, name=tr.name, args=args, result=trunc_str(tool_text(tr.text), mx=mx))
    if tr.server: res['server'] = True
    return "\n\n" + fenced(dumps(res, indent=2, ensure_ascii=False), tool_info) + "\n\n"

# %% ../nbs/00_msg_parts.ipynb #70d1e8c3
@patch(as_prop=True)
def formatted(self:Part): return self.text or ''
@patch
def doc(self:Part, showthink=False, mx=2000): return (self.text or '').strip()

@patch(as_prop=True)
def formatted(self:Thinking): return (self.text or '') if self.showthink else '🧠'
@patch
def doc(self:Thinking, showthink=False, mx=2000):
    if not (showthink and self.text): return ''
    return f'{think_start}\n::: details\n\n## Thinking\n\n{self.text.strip()}\n\n:::\n{think_end}'

@patch(as_prop=True)
def formatted(self:ToolUse): return '' if self.server else f"\n- ⏳ {_tc_summary(self)} ⏳\n"
@patch
def doc(self:ToolUse, showthink=False, mx=2000):
    "A server call's result is implicit, so it renders as a completed block; any other pending call is an ⏳ row"
    if not self.server: return self.formatted.strip()
    return mk_tr_details(self.replace(text='Server tool call executed.'), mx=mx).strip()

@patch(as_prop=True)
def formatted(self:ToolResult): return mk_tr_details(self)
@patch
def doc(self:ToolResult, showthink=False, mx=2000):
    "A result with no id can't be re-parsed into history (e.g. Gemini code execution), so it doesn't render"
    return mk_tr_details(self, mx=mx).strip() if self.id else ''

# %% ../nbs/00_msg_parts.ipynb #29e2b39b
@patch(as_prop=True)
def ctext(self:Part): return self.formatted

@patch(as_prop=True)
def ctext(self:Media): return _media_tag(self)

# %% ../nbs/00_msg_parts.ipynb #e5acd16a
def hist2fmt(msgs:list[Msg], mx=2000, showthink=False)->str:
    "Render assistant/tool `msgs` as one formatted output string, the inverse of `fmt2hist`"
    tus, out = {}, []
    for m in msgs:
        if m.role == 'assistant':
            for p in m.content:
                if isinstance(p, ToolUse) and not p.server: tus[p.id] = p
                else: out.append(p.doc(showthink=showthink, mx=mx))
        elif m.role == 'tool':
            for p in m.content:
                if not isinstance(p, ToolResult): continue
                tu = tus.pop(p.id, None)                       # results don't carry the call's arguments
                out.append(p.replace(arguments=tu.arguments if tu else {}).doc(mx=mx))
        else: raise ValueError(f"hist2fmt renders assistant and tool messages only, got {m.role!r}")
    out += [p.doc() for p in tus.values()]                     # calls still awaiting a result
    return '\n\n'.join(o for o in out if o)

# %% ../nbs/00_msg_parts.ipynb #d002a3ed
def mk_msg(
    content,      # Content: str, bytes (image), list of mixed content, or dict w 'role' and 'content' fields
    role="user"    # Message role if content isn't already a dict/Message
):
    "Create a LiteLLM compatible message."
    if content is None: return None
    if isinstance(content, Msg): return content
    if isinstance(content, Completion): return content.message
    if isinstance(content, list) and len(content) == 1 and isinstance(content[0], str): parts = [Text(content[0])]
    elif isinstance(content, list): parts = [mk_content(o) for o in content]
    elif isinstance(content, dict): return Msg(role=content['role'], content=[Text(content['content'])])
    else: parts = [Text(content)]
    return Msg(role=role, content=parts)

# %% ../nbs/00_msg_parts.ipynb #0ab86ef0
def mk_msgs(
    msgs    # List of messages (each: str, bytes, list, Msg, or Completion)
):
    "Create a list of fastllm canonical Msgs."
    if not msgs: return []
    if not isinstance(msgs, list): msgs = [msgs]
    msgs = L(msgs).map(lambda m: fmt2hist(m) if isinstance(m,str) and (tool_info in m or usage_info in m) else [m]).concat()
    res, role = [], 'user'
    for m in msgs:
        res.append(msg := mk_msg(m, role=role))
        role = 'assistant' if msg.role in ('user','tool') else 'user'
    return res
