"""The canonical LLM message model - `Msg`, `Part`, `ToolCall` - and its formatted text form

Docs: https://AnswerDotAI.github.io/aidialog/msg_parts.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_msg_parts.ipynb.

# %% auto #0
__all__ = ['PartType', 'tool_info', 'usage_info', 'think_start', 'think_end', 're_think', 'Part', 'Msg', 'ToolCall',
           'display_list', 'mk_tool_res_msg', 'sys_text', 'part_txt', 'data_url', 'url_mime', 'MediaUrl', 'parse_tools',
           'strip_tools', 'conv_tools', 'fmt2hist', 'StopResponse', 'FullResponse', 'mk_tr_details', 'hist2fmt']

# %% ../nbs/00_msg_parts.ipynb #a616b4f5
import base64, json
from json import dumps
from dataclasses import dataclass, field
from fastcore.utils import *
from fastcore.xtras import detect_mime

# %% ../nbs/00_msg_parts.ipynb #2212704a
@dataclass
class Part:
    "A normalized content part."
    type: str
    text: str = None
    data: dict = None

# %% ../nbs/00_msg_parts.ipynb #5342db55
PartType = str_enum('PartType', 'text', 'thinking', 'refusal', 'tool_use', 'server_tool_result', 'tool_result',
                    'input_image', 'input_audio', 'input_video', 'input_file')

# %% ../nbs/00_msg_parts.ipynb #026bfff6
def _trunc_strs(o, n=200):
    "Truncate str or dict"
    if not o: return o
    if isinstance(o,str) and len(o)>n: return o[:100]+'...'
    if isinstance(o,dict): return {k: (v[:100]+'...' if isinstance(v,str) and len(v)>n else v) for k,v in o.items()}
    return o

@patch
def _repr_markdown_(self: Part):
    body = _trunc_strs(self.text) if self.text else ''
    data = _trunc_strs(self.data)
    return f"""**Part** (`{self.type}`)

{body}

<details markdown='1'>

- data: `{data}`

</details>"""

# %% ../nbs/00_msg_parts.ipynb #ae349c18
@dataclass
class Msg:
    "A normalized message."
    role: str
    content: List[Part]

    @property
    def text(self): return ''.join(p.text or '' for p in self.content if p.type == PartType.text)

    def _repr_markdown_(self):
        return f"""**Msg**

- role: `{self.role}`

<contents>

{'\n\n'.join(p._repr_markdown_() for p in self.content)}

</contents>"""

# %% ../nbs/00_msg_parts.ipynb #3cbac5be
@dataclass
class ToolCall:
    "Normalized tool call."
    id: str
    name: str
    arguments: dict = field(default_factory=dict)
    server: bool = False
    extra: dict = field(default_factory=dict)

# %% ../nbs/00_msg_parts.ipynb #195b4d89
@patch
def _repr_markdown_(self: ToolCall):
    extra = _trunc_strs(self.extra)
    return f"""🔧 **{self.name}**(`{self.arguments}`)

<details markdown='1'>

- id: `{self.id}`
- server: `{self.server}`
- extra: `{extra}`

</details>"""

def display_list(l): 
    from IPython.display import Markdown, display
    display(Markdown('\n\n'.join(o._repr_markdown_() for o in l)))

# %% ../nbs/00_msg_parts.ipynb #7c88fce1
def mk_tool_res_msg(tool_calls:list[ToolCall], results:list[str|list]):
    'A util to prepare parallel tool call with str or media list results'
    parts = []
    for tc,res in zip(tool_calls, results):
        data = dict(id=tc.id, name=tc.name, arguments=tc.arguments, server=tc.server)
        parts.append(Part(type=PartType.tool_result, text=res, data=data))
    return Msg(role="tool", content=parts)

# %% ../nbs/00_msg_parts.ipynb #07b612b3
def sys_text(system):
    "Extract text from system (str or Part)."
    if system is None: return None
    return system if isinstance(system, str) else system.text

def part_txt(p): return p.text if isinstance(p,Part) else p

# %% ../nbs/00_msg_parts.ipynb #f30c7962
@flexicache(time_policy(24*3600))
def _fetch_url_partial(url, nbytes=512): 
    "Fetch remote media bytes, optionally only first `nbytes`."
    import httpx  # deliberately lazy: keeps aidialog's deps to fastcore alone (may re-base on fastcore.net later)
    try:
        with httpx.stream('GET', url, headers={'Range': f'bytes=0-{nbytes-1}'}, follow_redirects=True) as r:
            if r.status_code not in (200, 206): return
            return r.read()
    except (httpx.HTTPError, httpx.InvalidURL): return

# %% ../nbs/00_msg_parts.ipynb #b6f61273
_ext_mime = {
    '.jpg':'image/jpeg', '.jpeg':'image/jpeg', '.png':'image/png', '.gif':'image/gif', '.webp':'image/webp',
    '.pdf':'application/pdf',
    '.mp3':'audio/mpeg', '.wav':'audio/wav', '.ogg':'audio/ogg', '.flac':'audio/flac', '.m4a':'audio/mp4',
    '.mp4':'video/mp4', '.mov':'video/quicktime', '.webm':'video/webm',
}

def data_url(url):
    "Parse data:mime;base64,data URL into (mime, b64_data), or None."
    if not isinstance(url, str) or not url.startswith('data:') or ',' not in url: return None
    header, body = url.split(',', 1)
    if ';base64' not in header or not body: return None
    return header[5:].split(';',1)[0].strip() or 'application/octet-stream', body

def url_mime(url, default='application/octet-stream'):
    "Guess mime from URL extension, and optional bytes fallback."
    if "youtube.com" in url or "youtu.be" in url: return "video/mp4"
    ext = '.' + url.rsplit('.', 1)[-1].split('?')[0].lower() if '.' in url.split('?')[0].split('/')[-1] else ''
    if (mime:=_ext_mime.get(ext)) is None: return detect_mime(_fetch_url_partial(url))
    return ifnone(mime, default)

# %% ../nbs/00_msg_parts.ipynb #189772f5
class MediaUrl(BasicRepr):
    "Direct URL media reference"
    def __init__(self, url, mime=None): self.url, self.mime = url, ifnone(mime, url_mime(url))

# %% ../nbs/00_msg_parts.ipynb #859905d7
def _mime2part_type(mime):
    "Map MIME string to canonical PartType"
    if mime.startswith('image/'): return PartType.input_image
    if mime.startswith('audio/'): return PartType.input_audio
    if mime.startswith('video/'): return PartType.input_video
    return PartType.input_file

def _bytes2content(data):
    "Convert bytes to fastllm canonical content"
    mtype = detect_mime(data)
    if not mtype: raise ValueError(f'Data must be a supported file type, got {data[:10]}')
    encoded = base64.b64encode(data).decode("utf-8")
    return Part(type=_mime2part_type(mtype), text=f'data:{mtype};base64,{encoded}')

def _url2content(o):
    "Convert MediaUrl to fastllm canonical content"
    mime = o.mime or url_mime(o.url)
    return Part(type=_mime2part_type(mime), text=o.url, data=dict(mime=mime))

def _mk_content(o):
    if isinstance(o, str):        return Part(type=PartType.text, text=o)
    elif isinstance(o, bytes):    return _bytes2content(o)
    elif isinstance(o, MediaUrl): return _url2content(o)
    return o

# %% ../nbs/00_msg_parts.ipynb #ee9c825e
tool_info = 'json {.tool}'     # fence info string of a tool block: {id, name, args, result} (+server; `error` reserved)
usage_info = 'json {.usage}'   # fence info string of a usage block: UsageStats fields

def parse_tools(s):
    "Split `s` into `(text, data)` segments: `data` is a parsed `{.tool}` block dict, `None` for the final segment"
    res, pos = [], 0
    for info,body,start,end in fenced_blocks(s):
        if info != tool_info: continue
        try: d = json.loads(body)
        except Exception: continue
        res.append((s[pos:start], d))
        pos = end
    return res + [(s[pos:], None)]

def strip_tools(s, tools=True, usage=True):
    "Remove `{.tool}` (and `{.usage}`) blocks from `s`"
    out, pos = [], 0
    for info,body,start,end in fenced_blocks(s):
        if not (tools and info == tool_info) and not (usage and info == usage_info): continue
        out.append(s[pos:start])
        pos = end
    out.append(s[pos:])
    return ''.join(out)

think_start,think_end = '<!--think_start-->','<!--think_end-->'
re_think = re.compile(rf'{re.escape(think_start)}.*?{re.escape(think_end)}\n?', re.DOTALL)

# Frozen legacy envelope recognition, used only by `conv_tools`. These are the
# exact patterns fastllm shipped for the released `<details markdown='1'>`
# envelopes plus the never-released `::: {.details}` spelling.
_lg_tool_tag = "<details class='tool-usage-details' markdown='1'>"
_lg_token_tag = "<details class='token-usage-details' markdown='1'>"
_lg_tool_attrs, _lg_token_attrs = "{.details .tool-usage-details}", "{.details .token-usage-details}"
_lg_tools = re.compile(
    fr"^(?:{_lg_tool_tag}\n*(?:<summary>(?P<summ1>.*?)</summary>\n*)?\n*```json\n+(?P<json1>.*?)\n+```\n+</details>"
    fr"|(?P<fence>:{{3,}}) {re.escape(_lg_tool_attrs)}\n+(?:## (?P<summ2>.*?)\n+)?```json\n+(?P<json2>.*?)\n+```\n+(?P=fence)$)",
    flags=re.DOTALL|re.MULTILINE)
_lg_token = re.compile(
    fr"^(?:{re.escape(_lg_token_tag)}\n*<summary>(?P<tsumm1>.*?)</summary>\n*\n*`(?P<trepr1>.*?)`\n*\n*</details>"
    fr"|(?P<tfence>:{{3,}}) {re.escape(_lg_token_attrs)}\n+## (?P<tsumm2>.*?)\n+`(?P<trepr2>.*?)`\n+(?P=tfence)$)\n?",
    flags=re.DOTALL|re.MULTILINE)

def conv_tools(s):
    "Convert legacy tool/usage envelopes in `s` (both historical spellings) to the fenced JSON wire format. Idempotent."
    def _tool(m):
        tj = m['json1'] if m['json1'] is not None else m['json2']
        try: d = json.loads(tj.strip())
        except Exception: return m[0]
        call = d.get('call') or {}
        res = dict(id=d.get('id'), name=call.get('function'), args=call.get('arguments') or {}, result=d.get('result'))
        if d.get('server'): res['server'] = True
        return fenced(dumps(res, indent=2, ensure_ascii=False), tool_info)
    def _tok(m):
        summ = m['tsumm1'] if m['tsumm1'] is not None else m['tsumm2']
        det = m['trepr1'] if m['trepr1'] is not None else m['trepr2']
        return fenced(dumps(dict(summary=summ, detail=det), ensure_ascii=False), usage_info)
    return _lg_token.sub(_tok, _lg_tools.sub(_tool, s))

# %% ../nbs/00_msg_parts.ipynb #7ae2959f
_fence_back = '`````'
_result_re = re.compile(f'\n{_fence_back}result\n(.*?)\n{_fence_back}\n', re.DOTALL)


# %% ../nbs/00_msg_parts.ipynb #6d60c135
def _mk_result_fence(output): return f"\n{_fence_back}result\n{output}\n{_fence_back}\n"

def _split_msg_on_fences(msg):
    "Split an assistant Msg on result fences, return list of Msgs"
    if msg.role != 'assistant': return [msg]
    if not _result_re.search(msg.text): return [msg]
    res, asst_parts, tool_parts = [], [], []
    for msg_part in msg.content:
        if msg_part.type == PartType.thinking: asst_parts.append(msg_part)
        elif msg_part.type == PartType.tool_use: tool_parts.append(msg_part)
        elif parts := _result_re.split(msg_part.text or ''):
            for i,p in enumerate(parts):
                if not p: continue
                if i % 2 == 0: res.append(Msg(role='assistant', content=asst_parts+[Part(type=PartType.text, text=p.strip())]))
                else:          res.append(Msg(role='user', content=[Part(type=PartType.text, text=_mk_result_fence(p))]))
    if tool_parts: res.append(Msg(role='assistant', content=tool_parts))
    return res

def _split_fence_msgs(msgs):
    "Split all assistant msgs on result fences for wire protocol"
    res = []
    for m in msgs: res.extend(_split_msg_on_fences(m))
    return res

# %% ../nbs/00_msg_parts.ipynb #ade55a7b
def _extract_tool_parts(d:dict):
    "Build (tool_use_part, tool_result_part) from a parsed `{.tool}` block"
    # Skip server tool calls in deserialization (round trip issues with Gemini/Anthropic)
    if not d or d.get('server') or d.get('id') is None: return None
    tu = Part(type=PartType.tool_use, text=None, data=dict(id=d['id'], name=d['name'], arguments=d.get('args') or {}))
    tr = Part(type=PartType.tool_result, text=str(d.get('result')), data={'id': d['id'], 'name': d['name']})
    return tu, tr

# %% ../nbs/00_msg_parts.ipynb #916f8df0
def fmt2hist(outp:str)->list[Msg]:
    "Transform a formatted output string into fastllm canonical Msgs"
    if usage_info in outp: outp = strip_tools(outp, tools=False)
    if think_start in outp: outp = re_think.sub('', outp)
    if tool_info not in outp:
        msg = Msg(role='assistant', content=[Part(type=PartType.text, text=outp.strip() or '.')])
        return _split_msg_on_fences(msg)
    hist, asst_parts, tool_parts = [], [], []
    def flush():
        if tool_parts:
            hist.append(Msg(role='assistant', content=asst_parts.copy()))
            hist.append(Msg(role='tool',      content=tool_parts.copy()))
            asst_parts.clear()
            tool_parts.clear()
    for txt,d in parse_tools(outp.strip()):
        if txt and txt.strip():
            if tool_parts: flush()
            asst_parts.append(Part(type=PartType.text, text=txt.strip() or '.'))
        if d and (tp := _extract_tool_parts(d)):
            asst_parts.append(tp[0])
            tool_parts.append(tp[1])
    flush()
    if asst_parts: hist.append(Msg(role='assistant', content=asst_parts))
    if not hist: hist.append(Msg(role='assistant', content=[Part(type=PartType.text, text='.')]))
    result = []
    for msg in hist:
        if msg.role == 'assistant': result.extend(_split_msg_on_fences(msg))
        else: result.append(msg)
    if result[-1].role == 'tool': result.append(Msg(role='assistant', content=[Part(type=PartType.text, text='.')])) 
    return result

# %% ../nbs/00_msg_parts.ipynb #86265805
class StopResponse(str): pass
class FullResponse(str): pass

# %% ../nbs/00_msg_parts.ipynb #4f105e4d
def _trunc_str(s, mx=2000, skip=10, replace="TRUNCATED"):
    "Truncate `s` to `mx` chars max, adding `replace` if truncated; `mx=None` disables truncation"
    if mx is None or isinstance_str(s, ('FullResponse','Safe','PrettyString')): return s
    if not isinstance(s, str): s = str(s)
    s = type(s)(s.rstrip())
    if len(s)>2 and s[0]=='𝍁' and s[-1]=='𝍁':
        s = s[1:-1]
        if replace: return s
    if mx is None or len(s)<=mx: return s
    s = s[skip:mx-skip]
    ss = s.split(' ')
    if len(ss[-1])>150: ss[-1] = ss[-1][:5]
    s = ' '.join(ss)
    if skip: s = f"…{s}"
    s = f"{s}…"
    if replace: s = f"<{replace}>{s}</{replace}>"
    return s

# %% ../nbs/00_msg_parts.ipynb #3f2a30e7
def _trunc_content(content, mx):
    "Truncate tool result content, respecting '_full' flag"
    if isinstance(content, dict) and '_full' in content and len(content)==1: return content['_full']
    return _trunc_str(content, mx=mx)

# %% ../nbs/00_msg_parts.ipynb #f08c8cbd
def mk_tr_details(tr, mx=2000):
    "Create the `{.tool}` wire block for a tool call; `mx=None` disables truncation"
    args = {k:_trunc_str(v, mx=None if mx is None else mx*5) if isinstance(v, str) else v for k,v in tr.data['arguments'].items()}
    res = dict(id=tr.data['id'], name=tr.data['name'], args=args, result=_trunc_content(tr.text, mx=mx))
    if tr.data.get('server'): res['server'] = True
    return "\n\n" + fenced(dumps(res, indent=2, ensure_ascii=False), tool_info) + "\n\n"

# %% ../nbs/00_msg_parts.ipynb #e5acd16a
def hist2fmt(msgs:list[Msg], mx=2000)->str:
    "Render assistant/tool `msgs` as one formatted output string, the inverse of `fmt2hist`"
    tus, out = {}, []
    for m in msgs:
        if m.role == 'assistant':
            for p in m.content:
                if p.type == PartType.text and p.text: out.append(p.text.strip())
                elif p.type == PartType.tool_use: tus[p.data['id']] = p
        elif m.role == 'tool':
            for p in m.content:
                if p.type != PartType.tool_result: continue
                tu = tus.get(p.data['id'])
                d = dict(p.data, arguments=tu.data.get('arguments', {}) if tu else {})
                out.append(mk_tr_details(Part(type=PartType.tool_result, text=p.text, data=d), mx=mx).strip())
        else: raise ValueError(f"hist2fmt renders assistant and tool messages only, got {m.role!r}")
    return '\n\n'.join(o for o in out if o)
