"""Message and dialog rendering: one projection from `Message` to semantic fasttags, shared by every app that displays a dialog

Every app that displays a dialog reimplements the same interpretation: dispatch on `msg_type`, strip tool traffic from replies, render outputs with `application/javascript` dropped and LaTeX normalized, inline attachments, skip pinned messages. This module holds that interpretation once, as composable pieces (`md2ft`, `render_message`) plus `__ft__` patches so a `Message` or `Dialog` renders directly in fasttag contexts. Styling stays with each consumer: output is semantic, unstyled tags carrying `data-type`/`data-part` attributes as the stable styling contract. Requires `mdhtml` (the `render` extra).

Docs: https://AnswerDotAI.github.io/aidialog/render.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_render.ipynb.

# %% auto #0
__all__ = ['katex_cdn', 'math_mode', 'md2ft', 'katex_hdrs', 'render_message']

# %% ../nbs/05_render.ipynb #7dde2fc5
import base64, json
from fastcore.utils import *
from fastcore.xml import Div, Article, Header, Main, Pre, Script, Link, Img, NotStr, to_xml, FT
from fastcore.nbio import join_out
from html import escape
from mdhtml import to_mdhtml, to_html, theme_css, math_js
from .dialog import Dialog, Message, render_md, normalize_text_latex, snote, scode, sprompt, sraw
from .msg_parts import conv_tools, strip_tools

# %% ../nbs/05_render.ipynb #60f34192
_math_names = ('off','brackets','dollars')

def math_mode(use_katex):
    "0 for off or unparseable, 1 for truthy, 2 for 'd…' (dollar delimiters)"
    try: return 2 if isinstance(use_katex,str) and use_katex[:1].lower()=='d' else int(str2bool(use_katex))
    except TypeError: return 0

def md2ft(
    md,  # Markdown source (the `md` dialect)
    atts=(),  # `Attachment`s to inline as data URIs
    math_mode:int=0,  # 0 off, 1 bracket delimiters, 2 dollars
    fn_salt=''  # Salt for footnote ids, normally the message id
):
    "Convert markdown to fasttags"
    atts = {a.id:a for a in atts}
    def embed_attachment(n, html):
        if not n['url'].startswith('attachment:'): return
        if not (a := atts.get(n['url'].removeprefix('attachment:'))): return
        data = base64.b64encode(a.data).decode()
        return to_xml(Img(src=f'data:{a.content_type};base64,{data}', alt=n['alt'] or '', title=n.get('title')))
    return NotStr(str(to_html(to_mdhtml(md, math=_math_names[math_mode], callbacks=dict(image=embed_attachment)),
                              refs='ids', auto_ids=True, fn_salt=fn_salt)))

# %% ../nbs/05_render.ipynb #838078c6
katex_cdn = 'https://cdn.jsdelivr.net/npm/katex@0.16.22'

def katex_hdrs(math_mode):
    "KaTeX stylesheet and render script, or empty when math is off"
    if not math_mode: return ()
    js = f"import katex from '{katex_cdn}/dist/katex.mjs';\n" + math_js(fn='render', minRuleThickness=0.06) + '\nrender(document);'
    return Link(rel='stylesheet', href=f'{katex_cdn}/dist/katex.min.css'), Script(js, type='module')

# %% ../nbs/05_render.ipynb #9a18da65
def _hl(s): return NotStr(str(to_html(f'<pre><code class="language-python">{escape(s)}</code></pre>')))
def _mm(m): return getattr(m.dlg, 'math_mode', 0)

def _prep_out(o):
    if not (d := o.get('data')): return o
    d = {k:v for k,v in d.items() if k!='application/javascript'}
    if 'text/latex' in d: d['text/latex'] = normalize_text_latex(join_out(d['text/latex']))
    return {**o, 'data': d}

def _outputs(m):
    md = render_md([_prep_out(o) for o in m.output or []])
    return Div(md2ft(md, math_mode=_mm(m) or 1, fn_salt=m.id), data_part='output') if md else ''

def _msg_input(m):
    if m.msg_type in (snote,sprompt): return md2ft(m.content, m.attachments, _mm(m), fn_salt=m.id)
    if m.msg_type==sraw:              return Pre(m.content)
    if m.msg_type==scode:             return _hl(m.content)
    raise NotImplementedError(m.msg_type)

def _msg_output(m):
    if m.msg_type==scode: return _outputs(m)
    if m.msg_type==sprompt and (resp := m.ai_res): return md2ft(strip_tools(conv_tools(resp)), math_mode=_mm(m), fn_salt=m.id)
    return ''

def render_message(m):
    "One message as fasttags: input plus output, shaped by `msg_type`"
    inp,out = _msg_input(m),_msg_output(m)
    if m.msg_type==sprompt: return Header(inp), Div(out, data_part='reply') if out else ''
    return (inp,out) if out else inp

# %% ../nbs/05_render.ipynb #b10d36b0
@patch
def __ft__(self:Message): return Article(render_message(self), id=f'_{self.id}', data_type=self.msg_type)

@patch
def __ft__(self:Dialog): return Main(m for m in self.messages if not m.meta.get('pinned'))
